### ISSUE TITLE
2nd Backendmodule never works

### ISSUE THREAD

**Issue by DavidBruchmann** [cobwebch/external_import#1]
... in TYPO3 7.6.
The inclusion in ext_tables.php seems being wrong.

**Comment by fsuter** [comment]
I'm really puzzled by that, as I have the extension working in 3 different TYPO3 7 installations. What's wrong exactly according to you? Any error message?

**Comment by DavidBruchmann** [comment]
Sorry, the log-module works, so I've been not detailed enough what's wrong exactly.
When I switch the (first) import-module to "Tables without synchronization" then I get this message shown and still could provide a backtrace too:

Uncaught TYPO3 Exception
#1313855173: The controller "Module" is not allowed by this plugin. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php. (More information)

TYPO3\CMS\Extbase\Mvc\Exception\InvalidControllerNameException thrown in file
D:\___WWW___\_typo3\_SOURCES\typo3_src-7.6.15\typo3\sysext\extbase\Classes\Mvc\Web\RequestBuilder.php in line 215.

**Comment by fsuter** [comment]
Ah, I could reproduce that! ;-)

Thanks for reporting.

**Comment by DavidBruchmann** [comment]
thanks for the quick fix, is working.
