### ISSUE TITLE
mapping sys_category removes existing relations

### ISSUE THREAD

**Issue by abohntek** [cobwebch/external_import#100]
Hello,

I have an unspecific problem. I synch sys_categories for news. I extended the news tca with the appropriate ext settings: 

<pre>0 => [
        'field' => 'state',
        'MM' => [
            'mapping' => [
                'table' => 'sys_category',
                'referenceField' => 'title'
            ]
        ]
    ],
    1 => [
        'field' => 'organizer_title',
        'MM' => [
            'mapping' => [
                'table' => 'sys_category',
                'referenceField' => 'title'
            ]
        ]
    ],</pre>

Those two settings actually work perfectly, the extern titles matches with the sys_categories with the same title. But they always override each other and I dont have any clue, why. So if I ran both after each other, the second one always removes the current news category relations from the first one. I dont know how I can manage it to synch the categories from both external sources. It seems its just not possible. Do I am missing something or do I have to write my own UserFunc to get it work?

**Comment by fsuter** [comment]
Hi. Indeed existing MM relations are purged before new MM relations are mapped. This is much easier than mapping and then figuring which existing relations can be maintained, which are new and which should be deleted. It could be an interesting to be able to disable such purge on a per-column configuration basis. In the meantime it's probably best if you work your way around this by writing a user function.

**Comment by abohntek** [comment]
I wrote my own user function and solved it. Thanks for the fast reply!
