### ISSUE TITLE
Import FAL media files from RSS to tx_news

### ISSUE THREAD

**Issue by m-schmitz** [cobwebch/external_import#104]
Hi, first of all a big thank you for this great extension. Today I am fighting with the import of an RSS feed into tx_news, more specific with the import of the "enclosure" to fal_media. Since you reported, that the DataHandler knows how to handle sys_categories through the TCA, maybe I am missing out the key point (all other fields work like a charm). 

Currently I was trying to call a userFunc which cURLs the file from another server, adds the file to the sys_file via ResourceFactory and finally returns the new uid of the entry in sys_file. Do you think this is the right approach or do you recommend a different set up? Maybe you have any code samples that do something similar?

I would appreciate some small hints to push me into the right direction.

**Comment by fsuter** [comment]
Actually I have rarely imported files and I don't have much to offer as help. The sure thing is that External Import does not provide anything out of the box. Your approach using a userFunc for each file and returning the new file's uid is correct. I'm just not sure if simply setting the sys_file uid as value to store is enough.

**Comment by m-schmitz** [comment]
Thx for your quick reply. I did not manage it so far (customer requirements changed), but when I get to manage it, I will add my solution here

**Comment by fsuter** [comment]
This is actually duplicated by #68, so I'm closing it for now. I will soon launch a funding round for this feature. Stay tuned.
