### ISSUE TITLE
Differentiate nodes

### ISSUE THREAD

**Issue by webian** [cobwebch/external_import#107]
Hi François!
I encountered an use case where the external system can send 2 types of xml with the list of products:
1. full
2. incremental

Simplified structure if full:
```
<ErpProducts>
  <Products>
    <Product>
       product fields
```

Simplified structure if incremental:
```
<ErpProducts>
  <UpdatedProducts>
    <Product>
       product fields
  <DeletedProducts>
    <Product>
       product id
```

I'm stuck on the incremental case because I can't find a way to differentiate  UpdatedProducts from DeletedProducts since I have to use `'nodetype' => 'Product'` to get the various products data.

Is it actually possible with external_import?
Thanks! :)

**Comment by fsuter** [comment]
Hi. This should be possible. What you need to do is set "UpdatedProducts" as the `nodetype` and then use the `xpath` property in the column configuration to query the child "Product" node.

**Comment by webian** [comment]
Thank you for the quick answer!

I'm not sure that I got you right but with data like this (3 updated products; 1 deleted product):
```
<ErpProducts>
  <UpdatedProducts>
    <Product>
       product fields
    <Product>
       product fields
    <Product>
       product fields
  <DeletedProducts>
    <Product>
       product id
```
if I set `'nodetype' => 'UpdatedProducts'` then https://github.com/cobwebch/external_import/blob/ad85dff67327802e9769d5c193e58d9cb300ebf7/Classes/Handler/XmlHandler.php#L54 returns 1 node. I can be wrong because I don't full understand how php handles xml but I guess this node is the full structure of `<UpdatedProducts>` so then maybe it's not possible to get the 3 updated products even with xpath. At least it doesn't seem to work.

I also tried to still set `'nodetype' => 'Product'` and then filter updated and deleted products with xpath and...
```
$GLOBALS['TCA']['products']['columns']['code']['external'][0] = [
    'xpath' => '/ErpProducts/UpdatedProducts/Product/Code',
];
```
returns 4 items all with the same code (the first child of UpdatedProducts node).
While...
```
$GLOBALS['TCA']['products']['columns']['code']['external'][0] = [
    'xpath' => '/ErpProducts/DeletedProducts/Product/Code',
];
```
still returns 4 items all with the same code (the first and only child of DeletedProducts node).

I try to better debug what's happening and then report back.

**Comment by webian** [comment]
I add that if I again set `'nodetype' => 'UpdatedProducts'` and a column config like:
```
$GLOBALS['TCA']['products']['columns']['code']['external'][0] = [
    'xpath' => '/ErpProducts/UpdatedProducts/Product/Code',
];
```
then it returns only the first child of UpdatedProducts node.

**Comment by fsuter** [comment]
Indeed, it won't work, I was over-optimistic. What you would need in your case is an Xpath at nodetype-level. I don't see easy solution to your problem. Maybe you could introduce a custom step before the "ReadData" step, where you extract the "UpdatedProducts" nodes substructure. Then the "ReadData" step could read each "Product".

**Comment by webian** [comment]
Following your advice, I solved this use case with a custom step after "readData" step. This custom step loads the xml from the raw data and, if incremental, deletes products in `DeletedProducts` node and then deletes this node and sets `disabledOperations = delete` to proceed with the import of `UpdatedProducts`.
Thanks for your help!
