### ISSUE TITLE
Environmental configuration 

### ISSUE THREAD

**Issue by gartenumgraben** [cobwebch/external_import#110]
There are some configuration parts that should be configurable by environment (dev, test, prod ...) or even by contents in BE.

For example:

If one runs multiple imports for multiple tables each of which to be using a different pid, the only current solution is to set this up in TCA. This seems wrong as a folder is subject of content management in BE and thus shall not be set in code. 

Is there a propper way to handle this? I know that one can set the pid in the extconfig, but thats only one pid while you might need mulitple pids for individual imports :-(

Same goes for svconnector parts (e.g. json location etc.)

**Comment by fsuter** [comment]
I can understand that this feels wrong somehow. There's currently no proper way.

Could describe your use case in more details? What exactly do you need? How do you imagine setting the pids ideally?

This might give me some ideas on how this could be implemented (although I don't promise anything, I support this extension in my free time).

**Comment by gartenumgraben** [comment]
It's a general use case where in "bigger" projects I need to access multiple external sources/services/serviceparts that imports to a different folder each - e.g. one that provides products (to product folder) while an other provides news (to news folder).

You could use TS but that's not as "easy" in backend context for several reasons as you might know. 

You could also use marker/placeholders since TYPO3 does so within TCA as well. So I could set the "pid" option in my TCA config to some marker like "###pid_product"### or "###pid_news###" or whatever I choose. In extconfig you could provide a new setting "markers" as textfield allowing to set markers e.g.:

pid_product:12
pid_news:34

Thats for the easy ones. A more complex approach would be using a persistent config as for example the scheduler does, but that would require some more work.

**Comment by fsuter** [comment]
Hi,

If this situation that you described a long while ago is still an issue for you, you might want to look at that feature, which was introduced recently: https://github.com/cobwebch/external_import/issues/265

Also have you considered using environment variables, which you can set in a separate file using https://packagist.org/packages/helhum/dotenv-connector? You can then refer to those variables in the External Import configuration using `getenv()`.

I would really avoid using TypoScript in the backend, but with the 2 above tools/features I could solve most of my needs.

I hope this helps you and I will close this request as I don't expect to implement anything more in this area for now. Feel free to reopen it if you disagree or if you have come up with some clever idea for flexible configuration.
