### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by droomdre** [cobwebch/external_import#118]
This is what you guys wrote int he documentation:
`$GLOBALS['TCA']['fe_users']['columns']['starttime']['external'] = array(
                0 => array(
                                'field' => 'start_date',
                                'transformations' => array(
                                                10 => (
                                                                'userFunc' => array(
                                                                                'class' => \Cobweb\ExternalImport\Task\DateTimeTransformation::class,
                                                                                'method' => 'parseDate'
                                                                )
                                                )
                                )
                )
);`

but it should be:
`$GLOBALS['TCA']['fe_users']['columns']['starttime']['external'] = array(
                0 => array(
                                'field' => 'start_date',
                                'transformations' => array(
                                                10 => array (
                                                                'userFunc' => array(
                                                                                'class' => \Cobweb\ExternalImport\Task\DateTimeTransformation::class,
                                                                                'method' => 'parseDate'
                                                                )
                                                )
                                )
                )
);`

Adding "array" after 10

**Comment by fsuter** [comment]
Absolutely! Thanks for reporting.
