### ISSUE TITLE
Fields are not taken into account if not from fe_users

### ISSUE THREAD

**Issue by droomdre** [cobwebch/external_import#120]
I'm using femanager and this adds some fields like: gender, date_of_birth. I also have an femanager_extended with some additional fields.
I wanted to update these fields which are not in fe_users but i could never see them in the "Handledatastep". After a long debugging i found out that all fields incorporated from other extensions than fe_users are not taken into account. I have to added these fields in my externalimport_tut/Configuration/TCA/Overrides/fe_users.php and deactivate the extension like femanager, femanager_extended for the whole thing to work.
May be there is an option i missed where one can tell external_import to check for TCAs.

**Comment by fsuter** [comment]
External Import normally takes into account all the TCA that is available, including whatever fields were added by extensions. What I suppose in your case is that there's an issue with the extension loading order. "externalimport_tut" is loaded before "femanager" and "femanager_extended". To avoid that, you should add a dependency on "femanager" and "femanager_extended" in "externalimport_tut", so that they get loaded first.

And BTW you should really not put your custom stuff into "externalimport_tut". If you update this extension, your changes will be lost. You should create your own custom extension instead.

**Comment by droomdre** [comment]
Yeah u r right. But this import is for this one particular project and it will be finish by the end of the month so i tought i could use the externalimport_tut to make things go faster.
I've added the dependecy in ext_emconf.php and the composer.json and i can see the fields now

**Comment by bh-teufels** [comment]
i am facing the same issues. 
but where i put the dependencies if i don't want to put that in externalimport?

i have the Extensions
femanager, femanager_extended, externalimport and my site-package extension

**Comment by fsuter** [comment]
Hi. external_import does not matter in that case. You should put your TCA in the site package extension and make that extension depend on femanager_extended. HTH.

**Comment by bh-teufels** [comment]
that is already the case.

- in the femanager_extended i add a field "position" to the fe_user table
- in my site package extension i have femanager_extended in the composer.json requirement and in ext_emconf.php depends
- in my site package extension i have the TCA for the external_import configuration with the mapping of the field "position"
`$GLOBALS['TCA']['fe_users']['columns']['position']['external'] = [
        0 => [
            'field' => 'position'
        ]
    ];`
    
but the field "position" is missing on "Column Mapping" in the Backend and did not get imported

**Comment by bh-teufels** [comment]
i deactivated external_import and reactivate it in the Backend - now it is working
*this workaround will not work with TYPO3 11

**Comment by fsuter** [comment]
I'm glad that you found a solution, but it shouldn't be necessary to deactivate et reactivate external_import. Perhaps what this has done is to rewrite the PackagesStates.php file and thus update your dependencies...

BTW if femanager_extended is also a custom extension of yours, you can put the external_import configuration there.
