### ISSUE TITLE
Take a change referenceField

### ISSUE THREAD

**Issue by droomdre** [cobwebch/external_import#125]
Hello,
in my first table import, i had to prefix the reference field:

`$GLOBALS['TCA']['tx_ext_domain_model_order_item']['columns']['tx_externalimporttut_externalid']['external'] = [

    0 => [
        'field' => 'uid',
        'transformations' => [
            10 => [
                'userFunc' => [
                    'class' => \Cobweb\ExternalimportTut\Transformation\NameTransformation::class,
                    'method' => 'prefixNewsUid' //added 'EK-'before the uid
                ]
            ]
        ]
    ]
]`

Now in the second Table-Import, i would like to reference to the previously created Item:
`$GLOBALS['TCA']['tx_ext_domain_model_order_tax']['columns']['item']['external'] = [

    0 => [
        'field' => 'uid',
        'transformations' => [
            10 => [
                'mapping' => [
                    'table' => 'tx_ext_domain_model_order_item',
                    'referenceField' => 'tx_externalimporttut_externalid'
                ]
            ]
        ]
    ]
]`
This won't work since the externalid have an "EK-" before. Is this a possibility to solve this?
Thank you.

**Comment by fsuter** [comment]
Well, you're lucky, the latest version (released yesterday) just makes it possible. You should be able to achieve what you want you want with a code like:
```
0 => [
    'field' => 'uid',
    'transformations' => [
        10 => [
            'mapping' => [
                'table' => 'tx_ext_domain_model_order_item',
                'referenceField' => 'CONCAT(\'EK-\', tx_externalimporttut_externalid)'
            ]
        ]
    ]
]
```
This is untested, because it's not a feature that I introduced myself and I haven't used it personally yet, but it's supposed to work.

**Comment by droomdre** [comment]
wow. u guys are awesome. Seems like this gonna work but i can't test it right coz i have another issue with slug. Don't know where this is coming from. i get the following when trying to synchronise:
An exception occurred while saving the data: An exception occurred while executing 'SELECT `uid`, `pid`, `slug`, `t3ver_state` FROM `tx_ext_domain_model_order_item` WHERE (`slug` = ?) AND (`t3ver_wsid` IN (?)) AND (`pid` <> ?) AND (`tx_ext_domain_model_order_item`.`deleted` = 0)' with params ["default-b41c6e0d4a", 0, -1]: Unknown column 'slug' in 'field list' (code: 0, location: /home/.../typo3_src-9.5.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php at line 60)

but when i check with readData oder Store-data steps, everything looks fine.

**Comment by fsuter** [comment]
Does your table have a slug field? Did you activate the new "updateSlugs" property from the latest version of external_import?

**Comment by droomdre** [comment]
seems like the problem comes from another extension using slugs. Deactivating the extension removes the error but i have no idea why this interferes with my extension. Unfortunately the CONCAT() doesnt work or may be i need other adjustments.

**Comment by fsuter** [comment]
I just made a quick try using CONCAT() and it works for me. You should try debugging. If you look into class MappingUtility, you can add debug statements on `$row` for each iteration (after line 231) and also debug the resulting mapping array `$localMapping` (before line 240).
You can use `var_dump` and run the import from the command line.

**Comment by droomdre** [comment]
Btw it would be really nice if this can work. And also something like:
`$GLOBALS['TCA']['tx_ext_domain_model_order_tax']['columns']['tx_externalimporttut_externalid']['external'] = [
    0 => [
        'field' => 'CONCAT(uid_foreign, tx_externalimporttut_externalid)'
    ]
];`

**Comment by droomdre** [comment]
Ok i will check this again. Are you also planing to allow something like:
`$GLOBALS['TCA']['tx_ext_domain_model_order_tax']['columns']['tx_externalimporttut_externalid']['external'] = [
    0 => [
        'field' => 'CONCAT(uid_foreign, tx_externalimporttut_externalid)'
    ]
];`

**Comment by fsuter** [comment]
Not at all. This is very specific and would apply only to SQL-based sources, whereas external_import aims to be as generic as possible using Connector services. Your need is exactly why user functions exist (so it absolutely correct that you used one).

**Comment by droomdre** [comment]
Yes you are right. I'll better use user functions and this is what i did. My External ID is now a combination of uid and uid_foreign in tx_ext_domain_model_order_product.
Now i can't reference to this in tx_ext_domain_model_order_item because the following throws an error:
`$GLOBALS['TCA']['tx_ext_domain_model_order_item']['columns']['products']['external'] = [

    1 => [
        'field' => 'uid_foreign',
        'transformations' => [
            10 => [
                'mapping' => [
                    'table' => 'tx_ext_domain_model_order_product',
                    'referenceField' => 'CONCAT(uid,\'_\',uid_foreign)'
                ]
            ]
        ]
    ]
];`
The requested configuration was not found (table: tx_ext_domain_model_order_item, index: 1). Message: An exception occurred while executing 'SELECT CONCAT(uid,'_',uid_foreign), uid FROM `tx_ext_domain_model_order_product` WHERE (1 = 1) AND (`tx_ext_domain_model_order_product`.`deleted` = 0)': Unknown column 'uid_foreign' in 'field list' [0]

May be i'm doing it wrong?

**Comment by droomdre** [comment]
ok i got it, i add a `, CONCAT(tx_occheckout_orders.uid,'_',uid_foreign) as uid_uid_foreign` to my sql-statement im Connector and then i could do:
```
$GLOBALS['TCA']['tx_ext_domain_model_order_item']['columns']['products']['external'] = [
1 => [
    'field' => 'uid_uid_foreign',
    'transformations' => [
        10 => [
            'mapping' => [
                'table' => 'tx_ext_domain_model_order_product',
                'referenceField' => 'tx_externalimporttut_externalid'
            ]
        ]
    ]
]
];
```

**Comment by fsuter** [comment]
Glad that you found a solution. Your first try indeed would not have worked. The `CONCAT` function is a bit particular. When you want to concatenate several fields, you need to use `CONCAT_WS` instead. So your code would be:
```
'referenceField' => 'CONCAT_EW(\'_\', uid, uid_foreign)'
```

**Comment by droomdre** [comment]
ok thank you. I'll keep that in mind
