### ISSUE TITLE
Import to mm-Table

### ISSUE THREAD

**Issue by droomdre** [cobwebch/external_import#126]
The last work for my project migration would be to add values to a mm-table.
When a fe_user watchs a video, There is an entry added to tx_newsextended_user_news_mm. Additionally there is a count on "watched_news" in fe_users.
The column is defined as follow:
` 'watched_news' => array(

        'exclude' => 1,
        'label' => 'LLL:EXT:femanagerextended/Resources/Private/Language/locallang_db.xlf:tx_femanagerextended_domain_model_user.watched_news',
        'config' => array(
            'type' => 'inline',
            'foreign_table' => 'tx_news_domain_model_news',
            'foreign_field' => 'uid_foreign',
            'foreign_table_where' => 'AND tx_news_domain_model_news.deleted!=1 AND tx_news_domain_model_news.hidden!=1',
            'MM' => 'tx_newsextended_user_news_mm',
            'size' => 10,
            'autoSizeMax' => 30,
            'maxitems' => 9999,
            'multiple' => 0,
            'appearance' => array(
                'enabledControls' => array(
                    'new' => false,
                )
            )
        ),
    )`

The table i want to import is a kind of mm too and looks as follow:

|uid|news_id|user_id|
--------------------
|1  | 3          | 4        |
--------------------

Now i tried as following:
`$GLOBALS['TCA']['fe_users']['columns']['watched_news']['external'] = [

    1 => [
        'field' => 'event_id',
        'MM' => [
            'mapping' => [
                'table' => 'tx_news_domain_model_news',
                'referenceField' => 'external_id',
            ],
            'sorting' => 'uid'
        ]
    ]
];`

I have no idea how to solve this. Is this possible to import a mm-table to another mm-table and in my case both values "news_id" and "user_id" from the table to import has be mapped and both have new values to reference to.

**Comment by fsuter** [comment]
Hi. It is possible, but that's not what the `MM` property is for (I guess this is the most confusing configuration option; I have to find something better in the future...). A simple mapping with the `transformations` property will do the job. So your code would look like:
```
$GLOBALS['TCA']['fe_users']['columns']['watched_news']['external'] = [
  1 => [
      'field' => 'event_id',
      'transformations' => [
        10 => [
          'mapping' => [
              'table' => 'tx_news_domain_model_news',
              'referenceField' => 'external_id',
          ],
        ]
      ]
  ]
];
```
and something similar for the "user_id".

**Comment by droomdre** [comment]
ok you are right. My mistake. I tought i had to enter values in the MM-Table (tx_newsextended_user_news_mm) but actually if i add elements to the column watched_news of fe_users, it should put the value in the mm-table right?
I tried as you told me. In Storedata- Debug Preview, i can see that only the first founded News-item will be added to the user. Not sure why he is not showing all the others news from the user to be added. May be it's just a view. Now when i synchronise, there is no data added nor to the mm-table neither to the fe_users-Table.

**Comment by fsuter** [comment]
I can see that my previous comment could lead to a mistaken configuration. You also need to have a column where you store the "imported" uid. This is the field that is referenced in the "referenceUid" property of the general configuration. If you don't have this information, External Import will not import any data.
Just create a simple integer field, call it "external_id" or something and store the value of the "uid" column (of your external data) in it.
I'm not sure if I'm clear enough. I hope so ;-)

**Comment by droomdre** [comment]
I think i got you. I have the external_id for my User already. The mapping also look correct in Store-Data-Step preview. I can see the mapped user receiving the mapped news. But if the user has two entries in the old table, i can see that only the first entry is taken and planed to be insert.

**Comment by fsuter** [comment]
I'm not sure to fully understand you. Were you making an observation or do you have a question?

**Comment by droomdre** [comment]
Actually it's an observation and a question. I'm not sure if it's intended. I would have expect the storedata-Step to show me all news which will get mapped but i can only see the first news mapped pro User and there is no entry in the mm-table. In the fe-user table i can that the "watched_news"-field has a 1meaning there is one news found

**Comment by fsuter** [comment]
No, it's not normal (nor intended). So, if we consider that you have this structure to import:
```
|uid|news_id|user_id|
|1 | 3 | 4 |
```
you need to map the first column to some "external_id" column, which will be your "referenceField". Then you map the second column to a news item and the third column to a fe_user. You should have as many entries as there are rows in your import data.
One thing: you need to make sure that your MM-table has a full TCA definition and not just the External Import configuration, otherwise nothing will be imported. It is unusual to do that, but required by External Import in this configuration (because you are saving directly to a MM-table).

**Comment by droomdre** [comment]
My MM-Table has a full TCA as i've put on my first post. Since i'm importing datas for fe_users from 2 differents tables, i have 2 external configurations.
The first configuration with 0 has 'referenceUid' => 'tx_cme_old_userid' and everything is mapped correct. I can import all user-datas from the first table to fe_users.
To import the second table, i have the second configuration 1. Also using 'referenceUid' => 'tx_cme_old_userid':

`$GLOBALS['TCA']['fe_users']['columns']['tx_cme_old_userid']['external'] = [

    0 => [
        'field' => 'uid'
    ],
    1 => [
        'field' => 'user_id'
    ]
];
`
`$GLOBALS['TCA']['fe_users']['columns']['watched_news']['external'] = [

    1 => [
        'field' => 'event_id',
        'transformations' => [
            10 => [
                'mapping' => [
                    'table' => 'tx_news_domain_model_news',
                    'referenceField' => 'external_id',
                ],
            ]
        ]
    ]
];`
The mapping look correct but only with the first founded news is taken and there is no entry in the mm-table
![grafik](https://user-images.githubusercontent.com/20789758/82250685-3260f280-994c-11ea-83cf-76f3b0597969.png)

**Comment by fsuter** [comment]
Ah... Sorry it seems like I misunderstood your setup from the beginning. It's very hard without seeing a complete setup. It was correct trying to use the `MM` property. Looking at the code sample in your first comment, the only thing I notice is the usage of "uid" for the `sorting` property. You need to make sure that the "uid" field is listed in the `additionalFields` property of the general configuration (https://docs.typo3.org/p/cobweb/external_import/4.1/en-us/Administration/GeneralTca/Index.html#additionalfields).
When you preview the data (as in your screenshot above), you should see a comma-separated list of news uid.
Sorry again for all the confusion.

**Comment by droomdre** [comment]
Oh cool. I now have the comma-separated list of news uid.
![grafik](https://user-images.githubusercontent.com/20789758/82258196-ae156c00-9959-11ea-94d6-252f428ad53b.png)
i can see the right amount in the fe-user table but there is no entries in the mm-table. Do i still miss sthg?

**Comment by fsuter** [comment]
Could it be a problem with your MM-table? Could you share its SQL definition? Is there any error message in the TYPO3 Log (not the External Import Log)?

**Comment by droomdre** [comment]
Yes i had a small error on my mm-table. Now it's working like a charm. Thank you so much

**Comment by fsuter** [comment]
Glad that you worked it out!
