### ISSUE TITLE
Default value of field if not present in source data

### ISSUE THREAD

**Issue by webian** [cobwebch/external_import#127]
Hi François!
I have an use case where the external system doesn't send a field if this is empty in its XML.

Example:
Mr. Bean write a text in the `note` field of its CRM and then send the record via XML to external_import that saves the note in TYPO3 DB.
Afterward, Mr. Bean deletes the text of the `note` and send the XML but its CRM doesn't put the `note` field in the XML because it's empty. Since there's not a `note` field in the record, external_import doesn't empty the field in TYPO3 DB.

The solution that I found is to trim transform the field so external_import force it to be empty and saves the update in TYPO3 DB. But I don't like this solution because I use `trim` for the wrong purpose.

Is there a better solution?

**Comment by fsuter** [comment]
I don't see a better solution for now.

I recently introduced a "default" property for the mapping configuration, which can be used for this, but it does not exist at column level. Another possibility could be to introduce a property specifically for handling the case of absent values, which is a quite common scenario after all.

**Comment by fsuter** [comment]
The feature introduced with https://github.com/cobwebch/external_import/issues/185 (which will be available in version 6.0.0, to be released after TYPO3 11) should solve this case. It makes it possible to detect an empty value in a flexible way and react to it by setting a default value, which could be an empty string. This should empty an already saved value, although I must admit that I haven't tested this particular scenario.

**Comment by fsuter** [comment]
Guessing from your "thumbs up" reaction, this works for you. Is that indeed the case? May I close this issue?

**Comment by webian** [comment]
Not tested yet because I'm still in TYPO3 10, but I guess that this can be closed. Thank you very much!

**Comment by fsuter** [comment]
That's weird, I received your comment in a mail notification, but I don't see it here. Maybe you deleted it?

External Import v6 is compatible with TYPO3 v10, so you can try it if you want to.

I'll close this issue, but feel free to reopen it if needed.

**Comment by webian** [comment]
Yes, I deleted it because I then realized that v6 is TYPO3 10 compatible. I will check this solution as soon as possible.
Thanks a lot for taking care of this issue.

**Comment by webian** [comment]
Hi @fsuter, I finally managed to test the new feature "isEmpty" and it works great in my use case.

I used a simple config like this and if the field is not present in the external source, the field is set to '' in TYPO3.
```
    'transformations' => [
        10 => [
            'trim' => 1
        ],
        20 => [
            'isEmpty' => [
                'default' => ''
            ]
        ]
    ]
```

I will never cease to be amazed by the way you work.
Thank you!
