### ISSUE TITLE
Empty Data Import Backend Module without Scheduler

### ISSUE THREAD

**Issue by eru-neo** [cobwebch/external_import#129]
Hi!
I am currently trying to set up the extension in our project. To get started, I wanted to implement a simple csv import, and I am using the documentation and the tutorial extension documentation as references.

The issue I'm facing is that the Backend Module "Data Import" is completely empty - no text or info - absolutely blank. I get no errors displayed or logged.
At first, I thought I would only see something once I configure a table for synchronization, but so far I haven't succeeded. So, I suppose my main question is: Is it normal to have a completely blank page on the Data Import BE module initially? If the answer is yes, I'll know I have to continue trying to find errors in my own configuration.
![image](https://user-images.githubusercontent.com/4334769/85831889-50addf80-b78f-11ea-8332-38cc3edbdfa0.png)

In case the empty screen is expected, and in the hopes that you might be able to point me in the right direction, here are some further details:
* typo3 version is 10.4.3
* extension was installed via composer
* extensions "external_import", "svconnector" and "scvonnector_csv" are active.
* The "Log" Module loads correctly (with no data available as expected, since I haven't run any syncs yet)
* "Connectors Test" Module also shows the csv connector and testing it over that interface works like a charm
* My TCA config seems to be loaded correctly:
![image](https://user-images.githubusercontent.com/4334769/85831313-61aa2100-b78e-11ea-867d-6508a57c3604.png)
* the corresponding table was created successfully and contains all relevant columns
![image](https://user-images.githubusercontent.com/4334769/85831683-f14fcf80-b78e-11ea-86f0-6d38a24c6af5.png)

Any advice is appreciated. I'm happy to provide any missing infos. Thank you!
Best regards,
Ernesto

**Comment by fsuter** [comment]
Hi. The empty screen is not expected. You should see at least a title and a message telling you that there's no matching configuration. So I would say that there's some unexpected error happening. Do you really have nothing in your PHP log?

**Comment by eru-neo** [comment]
Thank you for that quick reply! Sadly, there's nothing, my logs are completely clear. I've checked the typo3 logs and the php error.log. I'll keep digging to see if I find anything suspicious.

**Comment by fsuter** [comment]
Well, good luck! Another option would be to use XDebug or some such and see what happens, where the process gets stuck.

**Comment by eru-neo** [comment]
Hi, short update: By debugging I did find part of the problem, apparently my installation was missing typo3/cms-scheduler, so I installed it, and now I'm getting this error:

"PHP Fatal error: Class Cobweb\ExternalImport\Task\AutomatedSyncTask contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (TYPO3\CMS\Core\Resource\Processing\AbstractTask::isValidConfiguration, TYPO3\CMS\Core\Resource\Processing\TaskInterface::fileNeedsProcessing) in /var/www/html/public/typo3conf/ext/external_import/Classes/Task/AutomatedSyncTask.php on line 34" 

Did I install the wrong version of typo3/cms-scheduler maybe? I have 10.4
I seem to also have a debug config problem, as this error does not hit the logs, I only see it in the debug console, but that's another issue ^^.

**Comment by eru-neo** [comment]
Indeed if I add the two methods (isValidConfiguration, fileNeedsProcessing) to the AutomatedSyncTask class, the Backend Module works, so this is the problem. Apparently these 2 functions were added to the AbstractTask class on typo3/cms-scheduler:v10+.
I could downgrade typo3/cms-scheduler to v9, but that conflicts with my typo3 v10 requirements. 
What would you advise me to do? I can't actually change the class myself of course, that would only be a local fix as it is outside my project.

**Comment by fsuter** [comment]
Hi. Thanks for the debugging. The result is puzzling. `Cobweb\ExternalImport\Task\AutomatedSyncTask` does not implement `TaskInterface`. When I check things in my IDE, I see that `TaskInterface` is implemented by 4 task classes, none of which are related to External Import (all are related to resources/FAL).

Have you by any chance extended the `Cobweb\ExternalImport\Task\AutomatedSyncTask` class? Can you check the class inheritance/implementation of interfaces in your IDE?

**Comment by eru-neo** [comment]
Hi, thanks! Well, that is confusing indeed, but I guess we are getting closer. I checked in my IDE and what I see is that AutomatedSyncTask extends AbstractTask. AbstractTask is then taken from TYPO3\CMS\Core\Resource\Processing, and this class implements TaskInterface.

![image](https://user-images.githubusercontent.com/4334769/86084810-1188d280-ba9e-11ea-91ca-915664ed981b.png)
![image](https://user-images.githubusercontent.com/4334769/86084832-1fd6ee80-ba9e-11ea-9aa1-967a51dd232c.png)

Is this inheritance not what it should be?

**Comment by eru-neo** [comment]
Ok, that was it. The Abstract Class that AutomatedSyncTask extends should be `TYPO3\CMS\Scheduler\Task\AbstractTask`
but in my case, it was referencing `TYPO3\CMS\Core\Resource\Processing`
I'm not sure how it got switched, but I suppose it happened while I was trying to get it to work locally, and while I didn't have cms-scheduler in my system.

So, to recap in case this thread is ever useful for someone else: The only thing I was really missing originally was installing typo3/cms-scheduler in my system.

Thank you so much for your help, @fsuter !

**Comment by fsuter** [comment]
Great that you found out what it was.

This points to a bug, because I originally designed External Import so that it can work without the Scheduler, but obviously that's not possible. So either I can find a way to make it really independent or I must declare `typo3/cms-scheduler` as a dependency.

**Comment by fsuter** [comment]
I have tried to make the extension fully independent of `typo3/cms-scheduler` but the newer architecture of TYPO3 with clever reflection services makes it too difficult. There might be a way to achieve this, but I don't think it's worth it. It's easier to make External Import dependant on the Scheduler. However I think this is close to a breaking change, so I won't put it in now as a bugfix, but as a feature of the next major version.
