### ISSUE TITLE
Optional parameters for steps

### ISSUE THREAD

**Issue by mbrodala** [cobwebch/external_import#130]
Right now it is possible to register `customSteps` which supports a `class` and `position` option for each entry:

```php
'customSteps' => [
    [
        'class' => \Acme\Foo\CustomStep::class,
        'position' => sprintf('before:%s', \Cobweb\ExternalImport\Step\HandleDataStep::class),
    ],
],
```

It would be useful to have an `parameters` (or `params` to stay in sync) option here with optional arguments:

```php
'customSteps' => [
    [
        'class' => \Acme\Foo\CustomStep::class,
        'position' => sprintf('before:%s', \Cobweb\ExternalImport\Step\HandleDataStep::class),
        'parameters' => [
            'customOption' => 'foo',
        ],
    ],
],
```

These should be passed into the step as constructor arguments:

```php
namespace Acme\Foo;

use Cobweb\ExternalImport\Step\AbstractStep;

final class CustomStep extends AbstractStep
{
    public function __construct(array $parameters)
    {
        // use $parameters['customOption']
    }

    public function run()
    {
    }
}
```

This would make it easier to bundle options for custom steps compared to the current state where one needs to put them somewhere within `ctrl/external/<index>` for access.

**Comment by fsuter** [comment]
That would make sense. Thanks for the request.

**Comment by fsuter** [comment]
Note that I didn't pass the parameters as constructor arguments, because all the instantiation thingy will have to change in the near future with the new DI feature in TYPO3 10.

**Comment by mbrodala** [comment]
Nice one, thanks a lot. :-)
