### ISSUE TITLE
skip_rows 2 does not work

### ISSUE THREAD

**Issue by glucka** [cobwebch/external_import#132]
If i set the config skip_rows = 2 see always the following error message:
`The number of records (0) is below the required limit (3).`
With skip_rows = 1 work correctly.
I have 6 rows in csv.

**Comment by fsuter** [comment]
I have created a parallel issue in https://github.com/cobwebch/svconnector_csv/issues/9

**Comment by fsuter** [comment]
The issue has been resolves in svconnector_csv. When several rows were skipped, the last row skipped was used as header row, so this may have messed up your structure upon import.

I'll release svconnector_csv 2.4.1 right now. This bug should be solved. Please reopen it if that is not the case.
