### ISSUE TITLE
Mapping problem

### ISSUE THREAD

**Issue by DavidBruchmann** [cobwebch/external_import#14]
Having problems with MM-Mapping, the case is a bit complicated and divided in three import-steps.
All data come from one csv-file.
1. Step 1: All professions are imported in a table "tx_myextension_spezialisierung" but mapped from several cols into one field "spezialisierung". The mapping is crawling many rows of members just for the mapped fields, which are in detail:
'Spez01,Spez02,Spez03,Spez04,Spez05,Spez06,Spez07,Spez08,Spez09,Spez10,Spez11,Spez12,Spez13,Spez14,Spez15'
This import is working, from 3000 member-rows I get the ~30 entries in the table, so it's just refining the existing values.
2. Step 2: 
All members are imported with simple types like text and integers, queries are not imported. This import is working too.
3. Step 3: Now the professions of each person shall be mapped with MM-connections between the members-table and the table from step 1  "tx_myextension_spezialisierung".
Problem here is that for external['field'] I've no clear key to enter as the values are taken from all the 15 mapped fields. I tried with external['field']="spezialisierung" but that's not working and overwriting the members-table with useless and mostly empty data-rows. external['field'] expects a key from the csv-file, but as I mapped there 15 fields into one I'm struggling how to get the result.

**Comment by DavidBruchmann** [comment]
The csv-file is looking like this:
ID;Titel;Vorname;Nachname;Straße;Land;PLZ;Ort;Telefon;Telefax;Internet;E-Mail;Spez01;Spez02;Spez03;Spez04;Spez05;Spez06;Spez07;Spez08;Spez09;Spez10;Spez11;Spez12;Spez13;Spez14;Spez15
13095;Dipl.-Psych.;Vorname1;Nachname1;Straße1 21;D;10234;Ort1;101/12345678;;;name1@domain.com;Spezialisierung1;Spezialisierung2;;;;;;;;;;;;;
12584;Dr.med.;Vorname2;Nachname2;Straße2 23;D;11234;Ort2;102/12345678;;www.domain.com;name2@domain.com;Spezialisierung1;Spezialisierung3;;;;;;;;;;;;;
12617;Dipl.-Psych.;Vorname3;Nachname3;Straße3 22;D;12234;Ort3;103/12345678;103/12345678;www.domain.com;name3@domain.com;Spezialisierung1;Spezialisierung3;Spezialisierung4;Spezialisierung5;;;;;;;;;;;
12948;Dr.jur. Dipl.-Psych.;Vorname4;Nachname4;Straße4 27;D;13234;Ort4;104/12345678;104/12345678;;name4@domain.com;Spezialisierung1;;;;;;;;;;;;;;
14293;Dr.med.;Vorname5;Nachname5;Straße5 1;D;14234;Ort5;105/12345678;105/12345678;;theiss-abendroth@domain.com;Spezialisierung1;;;;;;;;;;;;;;
17854;Dr. phil.;Vorname6;Nachname6;Straße6 36a;D;15234 ;Ort6;106/12345678;;;;Spezialisierung1;;;;;;;;;;;;;;
9909;Dr. med.;Vorname7;Nachname7;Straße7 49;D;16234;Ort7;107/12345678;107/12345678;;name7@domain.com;Spezialisierung1;;;;;;;;;;;;;;
9911;Dipl.-Psych.;Vorname8;Nachname8;Straße8 2;D;17234;Ort8;108/12345678;108/12345678;;;Spezialisierung1;;;;;;;;;;;;;;
9913;Dipl.-Psych.;Vorname9;Nachname9;Straße9 48;D;18234;Ort9;109/12345678;109/12345678;;;Spezialisierung1;;;;;;;;;;;;;;
9915;;Vorname10;Nachname10;Straße10 44;D;19234;Ort10;110/12345678;110/12345678;;name10@domain.com;Spezialisierung1;Spezialisierung3;;;;;;;;;;;;;

**Comment by DavidBruchmann** [comment]
tca for table tx_myextension_spezialisierung (for import 1):
```

return array(
	'ctrl' => array(
       ...
              'external' => array(
			0 => array(
				'connector' => 'csv',
				'parameters' => array(
					'filename' => $importDatei,
					'delimiter' => ';',
					'text_qualifier' => '',
					'skip_rows' => 1,
					'encoding' => 'utf8',
					'utf8_with_bom' => true
				),
				'data' => 'array',
				'referenceUid' => 'spezialisierung', // ##### This is the name of a field in the TYPO3 CMS database, not in the external data! #####
				'priority' => 5,
				'description' => 'Import der Spezialisierungen',
				'additionalFields' => 'Spez01,Spez02,Spez03,Spez04,Spez05,Spez06,Spez07,Spez08,Spez09,Spez10,Spez11,Spez12,Spez13,Spez14,Spez15',
			)
		),
         ),
        'columns' => array(

		'spezialisierung' => array(
			'exclude' => 1,
			'label' => 'spezialisierung',
			'config' => array(
				'type' => 'input',
				'size' => 30,
				'eval' => 'trim'
			),
                         'external' => array (
            	             0 => array(
            		        'field' => 'spezialisierung'
            	            ),
                       ),
		),
        )
);
```
tca for table tx_myextension_mitarbeiter looks like this (Import 2 and 3):
```
return array(
	'ctrl' => array(
       ...
              'external' => array(
			0 => array(
				'connector' => 'csv',
				'parameters' => array(
					'filename' => $importDatei,
					'delimiter' => ';',
					'text_qualifier' => '',
					'skip_rows' => 1,
					'encoding' => 'utf8',
					'utf8_with_bom' => true
				),
				'data' => 'array',
				'referenceUid' => 'code', // ##### This is the name of a field in the TYPO3 CMS database, not in the external data! #####
				'priority' => 10,
				'description' => 'Import der Mitarbeiter',
				'enforcePid' => true,
				'disabledOperations' => '', 
			),
                       1 => array(
				'connector' => 'csv',
				'parameters' => array(
					'filename' => $importDatei,
					'delimiter' => ';',
					'text_qualifier' => '',
					'skip_rows' => 1,
					'encoding' => 'utf8',
					'utf8_with_bom' => true,
				),
				'data' => 'array',
				'referenceUid' => 'code', // ##### This is the name of a field in the TYPO3 CMS database, not in the external data! #####
				'priority' => 15,
				'description' => 'Import der Spezialisierungs-Mappings für Mitarbeiter.',
				'enforcePid' => true,
				'disabledOperations' => '', // [insert | update | delete]
				'additionalFields' => 'Spez01,Spez02,Spez03,Spez04,Spez05,Spez06,Spez07,Spez08,Spez09,Spez10,Spez11,Spez12,Spez13,Spez14,Spez15', // ID
				#'minimumRecords' => 1000,
			)
		),
         ),
        'columns => array(
            
		'titel' => array(
			'exclude' => 1,
			'label' => 'titel',
			'config' => array(
				'type' => 'input',
				'size' => 30,
				'eval' => 'trim'
			),
			'external' => array(
				0 => array(
					'field' => 'Titel'
				)
			)
		),
		'vorname' => array(
			'exclude' => 1,
			'label' => 'vorname',
			'config' => array(
				'type' => 'input',
				'size' => 30,
				'eval' => 'trim'
			),
			'external' => array(
				0 => array(
					'field' => 'Vorname'
				)
			),
		),
               .....
               
		'spezialisierung' => array(
			'exclude' => 1,
			'label' => '.spezialisierung',
			'config' => array(
				'type' => 'group',
				'internal_type' => 'db',
				'allowed' => 'tx_myextension_spezialisierung',   
				'MM' => 'tx_myextension_mitglieder_spezialisierung_mm',
				'size' => 6,
				'minitems' => 0,
				'maxitems' => 99,    // Spez01 - Spez15
				'multiple' => FALSE, // Allows the same item more than once in a list.
			),
			'external' => array(
				1 => array(
					'field' => 'Spez01', // ### EXTERNAL SOURCE (CSV) ###
					'MM' => array(
						#'multiple' => FALSE,
						'mapping' => array(
							'table' => 'tx_myextension_domain_model_spezialisierung',
							'reference_field' => 'spezialisierung'
						),
						# 'sorting' => 'spezialisierung',
					),
					'additionalFields' => 'Spez02,Spez03,Spez04,Spez05,Spez06,Spez07,Spez08,Spez09,Spez10,Spez11,Spez12,Spez13,Spez14,Spez15', // ID,
				)
			),
		),
        )
);
```

**Comment by DavidBruchmann** [comment]
I got it working, PUHHH!
Never remarked that in import 2 the "code"-field was empty, therefore import 3 produced bullshit.
For the field "code" in step 2 I included a mapping to allow "Id" as well as "ID" as cols in the CSV-file.
The hook-function then has to return "code" (beside other mapped fields) and not "Id" or "ID".
Step 3 of the import has to do then both mappings: code (Id, ID) and spezialisierung (Spez01 - Spez015).

**Comment by fsuter** [comment]
Hi. Sorry for not answering before. I had a couple of very busy days. Glad that you found out what was wrong. It seems to be quite a complicated scenario.

**Comment by DavidBruchmann** [comment]
Hi François,

don't mind, I got it working but nice that you're so concerned.
You're right, the setup is a bit complicated even it's only from one data-file, but your extension masters the import really in a cool way.
I digged in the the Import.php, so I know the source a bit now too.
The once mentioned timeouts I never experienced on the current server so the customer can work with it easily.

Greets,
David

**Comment by fsuter** [comment]
> I digged in the the Import.php, so I know the source a bit now too.

And you'll like the source of the next major version even better. I have totally refactored the Importer class (but it's not yet committed).

**Comment by DavidBruchmann** [comment]
good to hear, have now several customers where the extension is used or could be used.
Being curious ;-)

**Comment by fsuter** [comment]
The main changes have been committed now. If you want to try it out, you can check out the "wombat" branch.

**Comment by DavidBruchmann** [comment]
Thanks, being curious in any case and will have a look.
Is there something special related to my problems here? I thought my disability to make it right never needs an update from your side ... ;-)

**Comment by fsuter** [comment]
I don't think there's anything related to your issue, except that the mapping is now better isolated in its own class and maybe easier to investigate or debug when needed.

**Comment by DavidBruchmann** [comment]
Ok thanks, You still apply a new Tag to the new version?

**Comment by DavidBruchmann** [comment]
Sorry, missed the "4.0.0-dev" in wombat
