### ISSUE TITLE
DataTables error in "Log" module with TYPO3v9

### ISSUE THREAD

**Issue by mbrodala** [cobwebch/external_import#148]
Opening the *Log* module with TYPO3v9 yields the following error:

```
DataTables warning: table id=tx_externalimport_loglist -
Requested unknown parameter 'status' for row 0, column 0. For
more information about this error, please see
http://datatables.net/tn/4
```

**Comment by fsuter** [comment]
Well, it shouldn't be that different, but at least it means it's not a regression in the latest release. Maybe there's a malformed log entry (for whatever reason).

**Comment by mbrodala** [comment]
Yes, the issue also occurs on 4.3.3.

**Comment by fsuter** [comment]
Yes, the icons are fetched via the JS API. So one JS error will kill all the rest...

**Comment by fsuter** [comment]
I'm unable to reproduce. I really think that it is something with your data, but the extract of the JSON output shows that the status field is present for every record. Could it be some other field?

The datatables setup for the Log module expects the following columns:

- status
- crdate
- username
- configuration
- context
- message
- duration

Is this data present for all 10 records?

I'm afraid that I don't have any other clue. I generally encountered this error while developing when I screwed up the datatables configuration.

Also when new fields were introduced in 4.1.0, it was necessary to truncate the log table to eliminate old record with missing data.

**Comment by mbrodala** [comment]
I just had another look and now suddenly the list works just fine again:

![image](https://user-images.githubusercontent.com/5037116/97458681-394c5200-193b-11eb-8215-709534d83cc1.png)
