### ISSUE TITLE
record id is not keept when insert in scheduler context

### ISSUE THREAD

**Issue by lstephanws** [cobwebch/external_import#15]
Hello,
When scheduler task is executed (automatically), records are not inserted.
The array "$tce->substNEWwithIDs" is not filled with record ID (Importer.php, line 1387).

If the task is executed manually in the backend, all records are inserted.
Version (3.0.6) is used.

Best regards,
Loïc Stéphan

**Comment by DavidBruchmann** [comment]
The cli-user must have the right to access involved files, records, mounts
and tables. Is related also to pages, else nothing happens.

**Comment by lstephanws** [comment]
You're right, sorry for the inconvenience.
Thanks !

**Comment by fsuter** [comment]
Note that this will be much easier with TYPO3 v8, as there is a unique CLI user and it has admin rights :-)
