### ISSUE TITLE
Records get not deleted, when using children configuration

### ISSUE THREAD

**Issue by cheindl** [cobwebch/external_import#157]
I have configured a table to import an external data source, which includes sub-records, which a mapped with "children" configuration. But records are not getting deleted, when a record is missing in external data source.

The reason is the following:

StoreDataStep.php:347
$table variable is overwritten in loop

StoreDataStep.php:443
Overwritten $table variable is used for TCEMAIN command array, $table should be the actual table we are working on

**Comment by fsuter** [comment]
Thanks for reporting. Indeed that looks bad :grimacing:

Could you be more precise about what happens, so that I can design tests to cover the issue? Is it records from the main table which are not deleted when there are children records?

**Comment by fsuter** [comment]
Don't worry about the scenario, I figured it out. Interestingly I thought I had it covered, because it worked fine when running in Preview mode and I didn't test it the same way when not in Preview mode. Anyway it is fixed now and will be included in the upcoming 5.1.0 release.
