### ISSUE TITLE
Fatal error, incomplete object

### ISSUE THREAD

**Issue by c-holtermann** [cobwebch/external_import#158]
Hello I get this error on a rather old typo3 system. Any ideas?
~~~
Fatal error: TYPO3\CMS\Scheduler\Scheduler::cleanExecutionArrays(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;tx_externalimport_autosync_scheduler_Task&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /var/www/clients/client4/web47/web/typo3_src-7.6.32/typo3/sysext/scheduler/Classes/Scheduler.php on line 106
~~~

**Comment by fsuter** [comment]
Hmm, not precisely. To each registered Scheduler task corresponds a row in the database, with one field containing a serialized instance of the related task class. Such errors could happen after an update (of external_import) where the class definition has changed. Then the system fails matching the unserialized object with the class definition.
I would suggest deleting the task and creating it anew, and see if the error happens again.

**Comment by fsuter** [comment]
Is this issue resolved?

**Comment by c-holtermann** [comment]
Yes, thank you. I deleted the respective entries from table tx_scheduler_task. I will reinsert them manually afterwards.
