### ISSUE TITLE
some additional lines in Importer.php

### ISSUE THREAD

**Issue by DavidBruchmann** [cobwebch/external_import#16]
I added the lines starting with +.
Explanation is in the comment.
I don't know if this leads to problems with some cases but I got the right results with different imports, while without the lines some data are missing.

```
        if (!empty($this->tableTCA['ctrl']['sortby'])) {
            $tce->reverseOrder = true;
        }
+		// added by David Bruchmann 17,05,2017
+		// keys of $tceData[$table] are uids which are removed below
+		// because if keys are not constantly increasing upper values get lost
+		// uids are later nevertheless assigned
+		foreach($tceData as $table => $valueArray){
+			$tmpArray = array();
+			$n = 1;
+			foreach($valueArray as $tceDataArray){
+				$tmpArray[$n] = $tceDataArray;
+				$n++;
+			}
+			$tceData[$table] = $tmpArray;
+			unset($tmpArray);
+		}
        // Load the data and process it
        $tce->start($tceData, array());
```

**Comment by fsuter** [comment]
I must admit that I don't understand what your patch is about. What problem does it solve for you?

**Comment by DavidBruchmann** [comment]
I had an array like this:
```
array(
1 => array('myKey'=>$someValue),
2 => array('myKey'=>$someValue),
32 => array('myKey'=>$someValue),
3 => array('myKey'=>$someValue),
5 => array('myKey'=>$someValue),
)
```
The values for 5 and 32 have been missing in my import.
The patch is just assigning mounting integer-keys instead, so the uid's 1,2,3,32,5 are ignored at this place in code.
Probably it's better just to assign directly other keys above the location of my patch instead of my patch.
I haven't searched yet the location where the uid's below the patch are assigned, so I don't know 100% if they get always assigned even they are not used in the array, but I assume they get assigned just by the order of the key-value-pairs in the array.
So the patch solves the problem in my case but is probably a bad way how to solve the problem. Only if the uid's have to be taken as keys in some cases, my patch could be wrapped in a condition.

**Comment by DavidBruchmann** [comment]
seems giving some headaches ;-)
Perhaps I've to debug at more points what really happens without my code?

**Comment by fsuter** [comment]
Any updates on this?

**Comment by DavidBruchmann** [comment]
I never updated the extension in the project anymore, therefore I don't know if all your work would have an impact on this. For me it's still unclear if you even can understand and maybe reproduce the issue.

**Comment by fsuter** [comment]
Looking at that again, the solution seems really weird. The numerical keys in a TCE data array are supposed to correspond to uids of existing records, or else be prefixed with "NEW". So assigning renumbered keys looks really odd.

If you don't mind, I would propose closing this issue. It can always be reopened later if needed, and we could then look at your scenario more closely. Would that be ok?

**Comment by DavidBruchmann** [comment]
Yes the solution is odd, I can confirm that ;-)
Regrettable it was required.
If you feel it painful to leave the issue open, just close it - I will come up again with it if I have to update the extension :D

**Comment by fsuter** [comment]
Thanks. I'm in a cleanup mood, so closing the issue feels good ;-)
