### ISSUE TITLE
Some records are nor inserted(updated) when there are empty sys_file_reference

### ISSUE THREAD

**Issue by Oktopuce** [cobwebch/external_import#162]
When there are empty children files, parent record is not inserted.

If you have a json like this : 
`{
        {
            "id": 130,
            "nom": "Mon premier enregistrement",
            "photos": [
            ],
            "fichiers": [
            ],
        },
        {
            "id": 355,
            "nom": "Mon second enregistrement",
            "photos": [
                {
                    "filename": "20170622_121159.jpg",
                    "download_link": "https://url.bientot-disponible.com/photo/243",
                },
                {
                    "filename": "20170622_111319.jpg",
                    "download_link": "https://url.bientot-disponible.com/photo/244",
                }
            ],
            "fichiers": [
                {
                    "name": "RÈGLE DU JEU Cycle 3.pdf",
                    "download_link": "https://url.bientot-disponible.com/fichier/104",
                },
                {
                    "name": "RÈGLE DU JEU Cycle 2.pdf",
                    "download_link": "https://url.bientot-disponible.com/fichier/103",
                }
            ],
        },
        {
            "id": 378,
            "nom": "Mon troisième enregistrement",
            "photos": [
                {
                    "filename": "cd63-maison--ENS-decouverte-scolaire.jpg",
                    "download_link": "https://url.bientot-disponible.com/photo/265",
                }
            ],
            "fichiers": [
            ],
        }
}`

with TCA like this : 

`'photos' => [
    'label' => 'photos',
    'config' => \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::getFileFieldTCAConfig(
        'photos',
        [
            'appearance' => [
                'createNewRelationLinkTitle' => 'LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:images.addFileReference'
            ],
            'overrideChildTca' => [
                'columns' => [
                    'crop' => [
                        'description' => 'field description',
                    ],
                ],
                'types' => [
                    \TYPO3\CMS\Core\Resource\File::FILETYPE_IMAGE => [
                        'showitem' => '
                        --palette--;;imageoverlayPalette,
                        --palette--;;filePalette'
                    ],
                ],
            ],
        ],
        $GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext']
    ),
],
'files' => [
    'label' => 'files',
    'config' => \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::getFileFieldTCAConfig(
        'files',
        [
            'appearance' => [
                'createNewRelationLinkTitle' => 'LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:images.addFileReference'
            ],
            'overrideChildTca' => [
                'columns' => [
                    'crop' => [
                        'description' => 'field description',
                    ],
                ],
                'types' => [
                    \TYPO3\CMS\Core\Resource\File::FILETYPE_TEXT => [
                        'showitem' => '
                        --palette--;;imageoverlayPalette,
                        --palette--;;filePalette'
                    ],
                ],
            ],
        ],
        'pdf,doc,docx'
    ),
]`

and external_import configuration : 

`//==================================================================
// Photos
//==================================================================
$GLOBALS['TCA']['tx_ext_domain_model_table']['columns']['photos']['external'] = [
    '1' => [
        'field' => 'photos',
        'substructureFields' => [
            'photos' => [
                'field' => 'download_link'
            ],
            'photo_title' => [
                'field' => 'filename'
            ]
        ],
        'transformations' => [
            10 => [
                'userFunction' => [
                    'class' => \Cobweb\ExternalImport\Transformation\ImageTransformation::class,
                    'method' => 'saveImageFromUri',
                    'parameters' => [
                        'storage' => '1:photos',
                        'nameField' => 'photo_title',
                        'defaultExtension' => 'jpg'
                    ]
                ]
            ]
        ],
        'children' => [
            'table' => 'sys_file_reference',
            'columns' => [
                'uid_local' => [
                    'field' => 'photos'
                ],
                'uid_foreign' => [
                    'field' => '__parent.id__'
                ],
                'title' => [
                    'field' => 'picture_title'
                ],
                'tablenames' => [
                    'value' => 'tx_ext_domain_model_table'
                ],
                'fieldname' => [
                    'value' => 'photos'
                ],
                'table_local' => [
                    'value' => 'sys_file'
                ]
            ],
            'controlColumnsForUpdate' => 'uid_local, uid_foreign, tablenames, fieldname, table_local',
            'controlColumnsForDelete' => 'uid_foreign, tablenames, fieldname, table_local'
        ]
    ]
];

//==================================================================
// Files
//==================================================================
$GLOBALS['TCA']['tx_ext_domain_model_table']['columns']['files']['external'] = [
    '1' => [
        'field' => 'fichiers',
        'substructureFields' => [
            'files' => [
                'field' => 'download_link'
            ],
            'file_title' => [
                'field' => 'filename'
            ]
        ],
        'transformations' => [
            10 => [
                'userFunction' => [
                    'class' => \Cobweb\ExternalImport\Transformation\ImageTransformation::class,
                    'method' => 'saveImageFromUri',
                    'parameters' => [
                        'storage' => '1:files',
                        'nameField' => 'file_title',
                        'defaultExtension' => 'pdf'
                    ]
                ]
            ]
        ],
        'children' => [
            'table' => 'sys_file_reference',
            'columns' => [
                'uid_local' => [
                    'field' => 'files'
                ],
                'uid_foreign' => [
                    'field' => '__parent.id__'
                ],
                'title' => [
                    'field' => 'picture_title'
                ],
                'tablenames' => [
                    'value' => 'tx_ext_domain_model_table'
                ],
                'fieldname' => [
                    'value' => 'files'
                ],
                'table_local' => [
                    'value' => 'sys_file'
                ]
            ],
            'controlColumnsForUpdate' => 'uid_local, uid_foreign, tablenames, fieldname, table_local',
            'controlColumnsForDelete' => 'uid_foreign, tablenames, fieldname, table_local'
        ]
    ]
]`

When you import data, you have this : 
[0] => "Mon second enregistrement"
[1] => "Mon second enregistrement"
[2] => "Mon troisième enregistrement"

The problem is in file external_import/Classes/Handler/ArrayHandler.php, should have this I guess : 

`                $rows = array_filter($rows);
                if (count($rows) > 0) {
                    // First find the longest substructure result
                    $maxItems = 0;
                    foreach ($rows as $column => $items) {
                        $maxItems = max($maxItems, count($items));
                    }
                    // Add as many records to the import data as the highest count, while filling in with the values found in each substructure
                    // NOTE: this is not equivalent to a full denormalization, but is enough for the needs of External Import
                    for ($i = 0; $i < $maxItems; $i++) {
                        // Base data is the first entry of the $theData array
                        // NOTE: the first pass is a neutral operation
                        $data[$counter] = $data[$referenceCounter];
                        // Add a value from each structure field to each row, if it exists
                        foreach ($rows as $column => $items) {
                            if (isset($items[$i])) {
                                foreach ($items[$i] as $key => $item) {
                                    $data[$counter][$key] = $item;
                                }
                            }
                        }
                    }
                }
                $counter++;
            }
`

instead of this : 

`                if (count($rows) > 0) {
                    // First find the longest substructure result
                    $maxItems = 0;
                    foreach ($rows as $column => $items) {
                        $maxItems = max($maxItems, count($items));
                    }
                    // Add as many records to the import data as the highest count, while filling in with the values found in each substructure
                    // NOTE: this is not equivalent to a full denormalization, but is enough for the needs of External Import
                    for ($i = 0; $i < $maxItems; $i++) {
                        // Base data is the first entry of the $theData array
                        // NOTE: the first pass is a neutral operation
                        $data[$counter] = $data[$referenceCounter];
                        // Add a value from each structure field to each row, if it exists
                        foreach ($rows as $column => $items) {
                            if (isset($items[$i])) {
                                foreach ($items[$i] as $key => $item) {
                                    $data[$counter][$key] = $item;
                                }
                            }
                        }
                        $counter++;
                    }
                } else {
                    $counter++;
                }`

The incrementation of $counter is not at the right place.

**Comment by fsuter** [comment]
Thanks for the detailed reporting. I'll look into it.

**Comment by fsuter** [comment]
Would you urgently need a release? In general I try to gather a few fixes before releasing.

**Comment by Oktopuce** [comment]
It would be nice for me to have it at mid April but anyway I applied the patch with composer waiting for the new release.

**Comment by fsuter** [comment]
Release is done (version 5.1.1).
