### ISSUE TITLE
Import tags from comma separated fields

### ISSUE THREAD

**Issue by Pekkonen** [cobwebch/external_import#172]
Hi!
I have XML with many items,
Item can have attribute tags and my goal is create a table for tags and linked each item with tags.
Of course I need to prevent a duplication of tags.
```
 <adresse>
 <id>45</id>
<tags>tag1, tag2, tag3</tags>
</adresse>
 <adresse>
<id>46</id>
<tags>tag2, tag3, tag4</tags>
</adresse>
 <adresse>
 <id>47</id>
<tags>tag1, tag3, tag4</tags>
</adresse>
```
In tag table I need to create this rows
```
title, uid
tag1, 1
tag2, 2
tag3, 3
tag4, 4
```
And for my items I need to create MM records accordingly.
I think this is a usual question, but I can't make it with your extension.
This code doesn't work for me, but I think 'table' and  'reference_field' - error for me.
```
$GLOBALS['TCA']['tx_myext_domain_model_tag']['columns']['title']['external'] = [
    0 => [
        'field' => 'tags',
        'multipleRows' => true,
        'transformations' => [
            10 => [
                'mapping' => [
                    'table' => 'tx_myext_domain_model_tag',
                    'reference_field' => 'title',
                    'multipleValuesSeparator' => ','
                ]
            ]
        ]
    ]
];
```
Can I make this in one step - I mean fill table "tx_myext_domain_model_tag"
 and create relations in MM?

Thanks for any hints!

**Comment by fsuter** [comment]
Hi,
As far as I understand your setup, no you can't make it all in one step. It would take two: one for the tags and one for the other table that is related to tags.
Regarding the first step, with the comma-separated tags, this is currently not supported by External Import. You would need to create a custom step to extract all your tags and make them into an array of unique values.
After that, the second should work with the setup you shared above. Just remove the `multipleRows` property which makes no sense here.
It's always a bit hard to answer with having the whole setup, but I hope that it helps.

**Comment by Pekkonen** [comment]
Hi François!
Thanks for the answer!
Now it's clear!

**Comment by fsuter** [comment]
Has it worked out for you? May I close this issue?

**Comment by Pekkonen** [comment]
I'm working with this right now.
Am I right you suggest to use this https://docs.typo3.org/p/cobweb/external_import/master/en-us/Developer/Steps/Index.html here "You would need to create a custom step"?
About 2nd step - I'm manually filled tags table and trying to apply this config
```
$GLOBALS['TCA']['tx_myext_domain_model_tag']['columns']['title']['external'] = [
    0 => [
        'field' => 'tags',
        'transformations' => [
            10 => [
                'mapping' => [
                    'table' => 'tx_myext_domain_model_tag',
                    'reference_field' => 'title',
                    'multipleValuesSeparator' => ','
                ]
            ]
        ]
    ]
];

```

But I have an error
`Argument 1 passed to TYPO3\CMS\Core\Database\Query\QueryBuilder::selectLiteral() must be of the type string, null given, called in /home/site/public_html/stage.sitename/public/typo3conf/ext/external_import/Classes/Utility/MappingUtility.php on line 224`

**Comment by fsuter** [comment]
Yes, I mean this https://docs.typo3.org/p/cobweb/external_import/master/en-us/Developer/Steps/Index.html

For the second point, please use "referenceField" instead of "reference_field". This old syntax was deprecated and later removed. So it could be causing this error.

**Comment by Pekkonen** [comment]
Thanks for this. Now I have no errors in BE.
But still no MM records in my tx_myext_domain_model_tag_mm after the import.
When I manually adding tags in BE - everything is fine and I see MM record in table.

**Comment by fsuter** [comment]
It's hard to say what is going wrong without having more detail. The preview data for each step should be telling. Have you checked the preview data at each relevant step (that would be `ReadDataStep`, `HandleDataStep`, `TransformDataStep` and `StoreDataStep`)?

You have probably seen it, but you can also set preview data for custom steps: https://docs.typo3.org/p/cobweb/external_import/master/en-us/Developer/Steps/Index.html#preview-mode

I hope this helps a bit.

**Comment by Pekkonen** [comment]
I have a correct preview data.
E.g. after "TransformDataStep"
```
array(5 items)
   0 => array(empty)
   1 => array(1 item)
      title => '7,10,NEWee9e06d80dd34fe7809e' (28 chars)
   2 => array(1 item)
      title => '8,12,13' (7 chars)
   3 => array(empty)
   4 => array(1 item)
      title => '9,11' (4 chars)
```
And after "StoreDataStep"
```
array(3 items)
   data => array(1 item)
      tx_myext_domain_model_tag => array(4 items)
         NEW9b922d8678cb2171f4d3 => array(1 item)
            pid => 3 (integer)
         NEW39a02d2586b036113703 => array(2 items)
            title => '7,10,NEW1255a0647b0e9b4c3397' (28 chars)
            pid => 3 (integer)
         16 => array(1 item)
            title => '8,12,13' (7 chars)
         17 => array(1 item)
            title => '9,11' (4 chars)
```
We have all data to correctly save them in MM table. But something wrong

**Comment by fsuter** [comment]
A guess: the relations should not be stored in the "title" field. In your TCA, what is the name of the field in which the MM relation is defined?

**Comment by Pekkonen** [comment]
Hi François!
Can you explain what's wrong with my Preview Mode?
I checked your link https://docs.typo3.org/p/cobweb/external_import/master/en-us/Developer/Steps/Index.html#preview-mode
But can't correct set this
I trying to use this

```
 public function run(): void
    {
    ...
$this->getData()->setRecords($records);
        $this->setPreviewData($records);
            }
}

```
but with no success.
Now I can't see my step in selectbox "Choose process step to preview"

**Comment by fsuter** [comment]
Which version are you using? There was a bug about custom steps not being included in the selector which was fixed in 5.0.1.

**Comment by Pekkonen** [comment]
Thanks for this info!
I'm using 5.0.0 and will try to update to 5.0.1

**Comment by fsuter** [comment]
Is this resolved?

**Comment by Pekkonen** [comment]
Yes. 
Thanks!
