### ISSUE TITLE
JSON Import Problem

### ISSUE THREAD

**Issue by marexx** [cobwebch/external_import#173]
Hi,
I want to Import a JSON File.
$GLOBALS['TCA']['tx_news_domain_model_link']['external']['general'] = [
        0 => [
                'connector' => 'json',
                'parameters' => [
                        'uri' => 'https://###.prescreenapp.io/job/list/1lqnoa3biqbefym2agelvbv9x8umbga?format=json'
                ],
                'data' => 'array',
                'referenceUid' => 'handle',
                'enforcePid' => true,
                'priority' => 210,
                'pid' => 78,
                'group' => 'externalimport_tut',
                'disabledOperations' => 'delete',
                'description' => 'Import Jobs from Prescreen'
        ],
];

I get data at the ReadDataStep
but no data an the handleDataStep

![Bildschirmfoto 2021-04-21 um 10 58 14](https://user-images.githubusercontent.com/838095/115526627-8416a900-a290-11eb-86c1-a8ade18c8b83.png)

i just need the "jobs" to be imported

**Comment by fsuter** [comment]
Hi. It's a bit difficult to say without seeing the source data, but from what I can tell the elements that you want to import are in a sub-array (with the key `jobs`). External Import is not designed to handle that in array-format data, although I can see with your example that it would be a nice feature to add (and it would then offer the same possibilities as for xml-format data).

In the meantime, you best bet it so create a custom step that would come just after the `ReadDataStep` and that would take the `jobs` sub-array and make it the main array. It would do something like:
```
    public function run(): void
    {
        $this->getData()->setRecords(
            $this->getData()->getRecords()['jobs'];
        );
    }
```
I hope this helps.

**Comment by fsuter** [comment]
Feature request: https://github.com/cobwebch/external_import/issues/175

**Comment by marexx** [comment]
Thanx,
this is how my XML looks like:

`<data>
<company>###</company>
<totalResults>7</totalResults>
<currentStartDisplay>0</currentStartDisplay>
<jobs>
<job>
<title>Azubi Backstube (m/w/d)</title>
<handle>lwvduu2zvk9j960z1zmocqb0y27cfrc</handle>
<shortHandle>pov4zs8b</shortHandle>
<showUrl>https://###.jobbase.io/job/lwvduu2zvk9j960z1zmocqb0y27cfrc</showUrl>
<applyUrl>https://###.###..jobbase.io/apply/lwvduu2zvk9j960z1zmocqb0y27cfrc</applyUrl>
<applyAddress>application+job+pov4zs8b@jobbase.io</applyAddress>
<template>
<id>48317</id>
<name>Schaefers Backstube Custom Template - Azubi Bäcker</name>
</template>
<bannerUrl>https://###..prescreenapp.io/uploads/company/jobs/941342.jpg</bannerUrl>
<bannerFooterUrl>https://###..prescreenapp.io/uploads/company/job_banner_footer/48317.png</bannerFooterUrl>
<department>
<id>16</id>
<title>Produktion und Handwerk</title>
</department>
<city>
<id>35585</id>
<title>xx</title>
<country>Deutschland</country>
<countryCode>DE</countryCode>
<lat>50.9121507</lat>
<long>8.5301232</long>
<zip_code>35216</zip_code>
</city>`

**Comment by fsuter** [comment]
With such a structure, you can use the `nodetype` property. Set it to "job" and you should get an array of "job" nodes after the `HandleDataStep`. Obviously, you need to change connector and set the data type as "xml".

**Comment by marexx** [comment]
i can also OUput Json.. but nodetype seems to have no effect :-( i'll try again..

**Comment by fsuter** [comment]
Maybe looking at a sample configuration will help you: https://github.com/cobwebch/externalimport_tut/blob/master/Configuration/TCA/Overrides/tx_news_domain_model_news.php

**Comment by marexx** [comment]
Yes, this was my base..
but maybe the problem is, that i already have a tx_news import,
but i want to do another one..

**Comment by fsuter** [comment]
That is not an issue. You can have several configurations per table. See: https://github.com/cobwebch/externalimport_test/blob/master/Configuration/TCA/tx_externalimporttest_product.php

**Comment by marexx** [comment]
I found the Problem... XML import was fine. The Problem was an existing Hook, which removed the Data.. :-(
so it'w works..! Thanx

**Comment by fsuter** [comment]
Glad that you worked it out!

**Comment by marexx** [comment]
I've one more question :-)
I use the Hook "preprocessRawRecordset" to remove unwanted entries.. for another import..
how can i distinguish from which import i got the Data?

**Comment by fsuter** [comment]
First make sure your hook implements the `\Cobweb\ExternalImport\ImporterAwareInterface` (using the `\Cobweb\ExternalImport\ImporterAwareTrait`). Then you can use the following to get the current table and index that is being imported:
```
$this->importer->getExternalConfiguration()->getTable()
$this->importer->getExternalConfiguration()->getIndex()
```
and test those values.

**Comment by fsuter** [comment]
BTW for your scenario, a custom step is recommended. It has the advantage of being specific to a given configuration and you don't need to test which one is currently running. The "preprocessRawRecordset" hook will be deprecated in the next major version.

**Comment by marexx** [comment]
OK. thanx for the hint!
