### ISSUE TITLE
Adding header for GeneralUtility::getUrl() request in ImageTransformation::saveImageFromUri() 

### ISSUE THREAD

**Issue by Oktopuce** [cobwebch/external_import#178]
It would be nice to allow header when downloading image file in order to bypass serveur authorization for example.

It's very easy to do !

In TCA section ['transformations']['userFunction']['parameters'], just add a new 'header' section : 

    $GLOBALS['TCA']['tx_myext_domain_model_table']['columns']['image']['external'] = [
        'resource' => [
             ...
        ],
        'transformations' => [
            10 => [
                'userFunction' => [
                    'class' => \Cobweb\ExternalImport\Transformation\ImageTransformation::class,
                    'method' => 'saveImageFromUri',
                    'parameters' => [
                        'storage' => '1:myFolder',
                        'nameField' => 'image_title',
                        'defaultExtension' => 'jpg',
                        'headers' => [
                            'specific-header-key' => 'header value'
                        ]
                    ]
                ]
            ]
        ],
        'children' => [
            ....
        ]

And in Classes/Transformation/ImageTransformation.php, get the headers and use them with getUrl() method :

    $requestHeaders = null;
    if (isset($parameters['headers'])) {
        foreach ($parameters['headers'] as $name => $value) {
            $requestHeaders[$name] = $value;
        }
     }
     $file = GeneralUtility::getUrl($record[$index], 0, $requestHeaders, $report);

instead of : 

    $file = GeneralUtility::getUrl($record[$index], 0, null, $report);

**Comment by fsuter** [comment]
Nice idea.

It will take a bit more work, though, because as of TYPO3 10, `GeneralUtility::getUrl` does not take headers as arguments anymore, so they can't be passed along. One has to rely on GuzzleHttp directly (see for example: https://github.com/cobwebch/svconnector/commit/743a6e0ccbbe2c0552fd9eb82bb4038f6d4518a1)

**Comment by Oktopuce** [comment]
Ok I see, but it will disappear in V11 and not in V10.

[https://github.com/TYPO3/TYPO3.CMS/blob/10.4/typo3/sysext/core/Classes/Utility/GeneralUtility.php](url)

**Comment by fsuter** [comment]
Yes, that's true, but I'm currently working on the next major version of External Import, which will be targeted at TYPO3 10 and 11, and I'm not very keen on introducing code which will very soon be obsolete.

**Comment by fsuter** [comment]
I'm closing this request, as External Import now supports only TYPO3 11 and 12.
