### ISSUE TITLE
How can I select XML Children.

### ISSUE THREAD

**Issue by marexx** [cobwebch/external_import#180]
Hi,
This is a part of one Data-Entry:
`<custom_data_fields>
<custom_data_field>
<id>241582</id>
<name>Filialauswahl</name>
<form_label>Welche Filialen kommen für Sie in Frage?</form_label>
<values>
<value>
<value_id>162537052</value_id>
<value>BID</value>
<value_label>Biedenkopf </value_label>
</value>
<value>
<value_id>162537057</value_id>
<value>MR</value>
<value_label>Marburg</value_label>
</value>
<value>
<value_id>162537062</value_id>
<value>GI</value>
<value_label>Gießen</value_label>
</value>
<value>
<value_id>162537077</value_id>
<value>SOL</value>
<value_label>Solms</value_label>
</value>
<value>
`
i need to select all "value_label" for each entry.

I tried it with this:
'xpath' => 'custom_data_fields/custom_data_field/values'

but then i get every value, also 'value_id'.. 
and this doesn't seem to work:
'xpath' => 'custom_data_fields//value_label'
This returns just the first entry..

**Comment by fsuter** [comment]
To be sure that I understand, do you mean that there are several entries and that there are several values per entry? And you want to retrieve all values for each entry?

I think it may work with substructure fields: https://docs.typo3.org/p/cobweb/external_import/5.1/en-us/Administration/Columns/Index.html#substructurefields but it depends what you want to do with all those labels afterwards.

**Comment by marexx** [comment]
i Think you are right.

but how would i use substructurefields  in my case?
		'xpath' => 'custom_data_fields/custom_data_field/values/',
		'substructureFields' => [
			'value_label' => [
				'field' => 'value_label'
			]
		],

At the end, i just need a string with comma seperated list:
'Biedenkopf, Gießen, Solms'

**Comment by fsuter** [comment]
I see. In this case, there's no easy way out of it. You need to target the `<values>` tag as you did and put it through a user function, to extract all `<value_label>` nodes and concatenate their values.

You probably want your user function to receive the XML structure inside the `<values>` tag, so you should set: https://docs.typo3.org/p/cobweb/external_import/5.1/en-us/Administration/Columns/Index.html#xmlvalue

I hope this helps.

**Comment by marexx** [comment]
Thanx, that's it:
'		'xpath' => 'custom_data_fields/custom_data_field/values',
		'xmlValue' => true,
		'transformations' => [
			10 => [
				'userFunc' => [
					'class' => \Cobweb\ExternalimportTut\Transformation\LinkTransformation::class,
					'method' => 'description'
				]
			]
		]


And the PHP:
'		$text = strval($record[$index]);
		preg_match_all("'<value_label>(.*?)</value_label>'si",$text , $matches);
		$cities = '';
		foreach($matches[1] as $val)
		{
			$cities .= $val.", ";
		}
		return $cities;
