### ISSUE TITLE
remove News entries

### ISSUE THREAD

**Issue by marexx** [cobwebch/external_import#181]
I've a list of Jobs  to be imported to tx_news.
That works fine. but If jobs are removed from the feed.  How can i remove the coressponding News-Entry?

	1 => [
		'connector' => 'feed',
		'parameters' => [
			'uri' => 'https://yyyyyy.prescreenapp.io/job/list/1lqnoa3biqbefym2agelvbv9x8umbga?format=xml',
			'encoding' => 'utf8'
		],
		'data' => 'xml',
		'nodepath' => 'jobs/job',
		'referenceUid' => 'title',
		'enforcePid' => true,
		'pid' => 78,
		'clearCache' => 104,78,
		'priority' => 210,
		'group' => 'externalimport_tut',
		#'disabledOperations' => 'delete',
		'description' => 'Import of Prescreen Jobs'
	],

**Comment by fsuter** [comment]
That should work with the above configuration. You can actually remove the whole `disabledOperations`, since you don't want any operation to be disabled. Doesn't it work for you?

**Comment by fsuter** [comment]
Is this issue resolved? Can it be closed?

**Comment by marexx** [comment]
i think so..
