### ISSUE TITLE
Empty values handling

### ISSUE THREAD

**Issue by fsuter** [cobwebch/external_import#185]
Currently if a value is missing from the external data source, the corresponding field (of the corresponding DB row) will not received any value, whether on insert or update. This is sometimes problematic, in particular during an update operation, when the value existing in the DB should be reset to some default or nulled, rather than left as is.

The topic is not simple because of the following issues:

- it may be easy to check if a value is missing, but not so easy to decide if it's empty (could be `0`, `null`, `false`, an empty string, etc.). It would probably help if this was configurable, to fit various scenarios
- could it be that in some cases, it would be useful to have several scenarios (e.g. one reacting to a missing value, another reacting to `0`)?
- can a field actually be nulled in the TYPO3 DB (knowing that External Import relies on the TCE for data storage)?

It would probably make sense for such properties (or sets of properties) to be part of the transformations, so that:

1. several can be applied if needed
2. it/they can be applied in a chosen order

Please comment below, especially if you have had such use cases in the past.

**Comment by DavidBruchmann** [comment]
'0`, `null` or `false` must be configurable, perhaps even other default values, else database-errors might be thrown on updates.  
I can't remember having had an issue like this but it's long time ago that I used this extension, I never used `update` but only `delete` all data and writing new.  
I'm not informed about the current state, perhaps it's useful to offer a hook if not existing yet.

**Comment by fsuter** [comment]
The variability of what is considered empty could be handled by using the Symfony Expression Language. The first property of this feature would be an expression which would be evaluated to true or false, and actions would be triggered if the result is `true` (i.e. the value is considered empty). Possible actions could be to set a default value, to trigger an `InvalidRecordException` which would remove the entire record from the import process (this would actually be a separate feature, the `InvalidRecordException` could be thrown by user functions too) or call a user function for custom processing.

**Comment by fsuter** [comment]
Reference for the documentation: https://symfony.com/doc/current/components/expression_language/syntax.html

**Comment by fsuter** [comment]
Actually calling a user function is pointless, since developers can already evaluate data in whatever way they want inside a user function and react to it as they wish (including invalidating the current record since https://github.com/cobwebch/external_import/issues/198).
