### ISSUE TITLE
Problem with FAL-image-Data-import (copy from https://forge.typo3.org/issues/59484  with patch)

### ISSUE THREAD

**Issue by Padina14** [cobwebch/external_import#187]
RELATED TO https://forge.typo3.org/issues/59484

@joerg
I tried your example to adapt to my import-sketch.

My images are already in in the data-storage. I got the link to the image from an imported RTE-Field.

I tried to use the \Monsunmedia\Importmcmdata\Transformation\Transformation::class,
The logic is complex and without a little bit of documentation. I tried reverse engenierung, but I don't unterstand that stuff.

How have I to define the storage.
How define i the needed Field for the title in the workflow of external_import?

You combinte two complex techniques in your example. (FAL-rendering and

What will happen, if I make a second import. Will that import kill the old references? (Similiar to import of categoriees from diffrent resources)
I really don't understand your stuff.

There is not error/hint about Links, which can't be imported.
Quote Edit Delete #14
Updated by Dieter Porth less than a minute ago

    File local_history1.patch local_history1.patch added

Classs fails for filepathes, which refer to subdirectories in the storage
The following patch works for me. (Import only one image. I don't know, how to add a comma-separated list of image-pathes

$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['fal_media']['external'] = [
        'field' => 'fal_media',
        'transformations' => [
            20 => [
                'userFunction' => [
                    'class' => \MyVendor\MyExte\Transformation\ImageTransformation::class,  //patched classs
                    'method' => 'saveImageFromUri',
                    'parameters' => [
                        'storage' => '3:/', // Storage-Folder is locaed in the main root and no subfolder needed - I was misslead by the documentation for some time 
                        'defaultExtension' => 'jpg',
                    ],
                ],
            ],
        ],
        'children' => [
            'table' => 'sys_file_reference',
            'columns' => [
                'uid_local' => [
                    'field' => 'fal_media',
                ],
                'uid_foreign' => [
                    'field' => '__parent.id__',
                ],
                'tablenames' => [
                    'value' => 'tx_news_domain_model_news',
                ],
                'fieldname' => [
                    'value' => 'fal_media',
                ],
                'table_local' => [
                    'value' => 'sys_file',
                ],
            ],
            'controlColumnsForUpdate' => 'uid_local, uid_foreign, tablenames, fieldname, table_local',
            'controlColumnsForDelete' => 'uid_foreign, tablenames, fieldname, table_local',
        ],
    ]

**Comment by fsuter** [comment]
Hi. After reading your message, I'm not sure what exactly is your problem or your question. Could you clarify?

If possible, please check the Markdown guidelines: https://guides.github.com/features/mastering-markdown/, it would make your message more readable, in particular the code samples.

**Comment by Padina14** [comment]
I hope this will explain it better.

**My problem was:** 
The import of images with external_import won't work for me.
 
**What I want:** 
The class `Cobweb\ExternalImport\Transformation\ImageTransformation` 
1. don't show all exceptions and 
1. it is to special programmed and
1. the usesage of `substructureFields` with a CSV-import is unclear.   

**In Detail**
1. At first I thought about an configuration-bug of mine. My first mistake was the missunderstanding, the attribute _storage_  `3:db` mean the path `[docroot]/db/db/` of the storage `3`, which starts on `[docroot]/db/`. The class don't throw some exceptions but don't show anny informations of that in the scheduler. I understand my mistake after tracing the code. 
1. My second mistake was, that my files are located in a subfolders of the storage.
`[docroot]/db/someWhere/image.jpg` and `[docroot]/db/otherWhere/image.jpg`. Your class don't test for subdirectories, even if the field contains the name of the subpath.  I can't upload a patch here, so i used the TYPO3-Forge for uploading.

```
Index: web/typo3conf/ext/external_import/Classes/Transformation/ImageTransformation.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/web/typo3conf/ext/external_import/Classes/Transformation/ImageTransformation.php b/web/typo3conf/ext/external_import/Classes/Transformation/ImageTransformation.php
--- a/web/typo3conf/ext/external_import/Classes/Transformation/ImageTransformation.php	(date 1621162543599)
+++ b/web/typo3conf/ext/external_import/Classes/Transformation/ImageTransformation.php	(date 1621162543599)
@@ -140,6 +140,10 @@
                     $parameters['storage'] . '/' . $fileName
             );
         // If the file does not yet exist locally, grab it from the remote server and add it to predefined storage
+        } else if             ($this->storageFolders[$parameters['storage']]->hasFile($record[$index])) {
+            $fileObject = $this->resourceFactory->getFileObjectFromCombinedIdentifier(
+                $parameters['storage'] . '/' . $record[$index]
+            );
         } else {
             $temporaryFile = GeneralUtility::tempnam('external_import_upload');
             $file = GeneralUtility::getUrl($record[$index], 0, null, $report);

```
3. My third problem ist, the workflow of `substructureFields` is unclear. I get a csv-file, which contains the field `body`. The field body contains HTML and img-tags. I can extract the link and the title in a custom step, but i don't understand how to transfer this datas to  `substructureFields`.

**Comment by fsuter** [comment]
Hi. This is indeed far more clear :-)

About 1 and 2, the image transformation class can certainly be improved. It is provided as an example to be refined as needed by people who use it. It is next to impossible to provide a class that will fit every scenario. However, error reporting can certainly be improved. As for the subfolder issue I could take a look, because it seems quite a general need.

As for 3, it's a bit hard to say without knowing what you CSV structure looks like, but from what I understand, in a custom step, you extract a list of image URLs and titles. For these to be usable with the `substructureFields` property, you need to create a sub-array for each record, something like:
```
[
    0 => [
        'item' => 'some_key',
        'pictures' => [
            [
                'link' => 'http://xxx...',
                'title' => 'Foo',
            ],
            [
                'link' => 'http://yyy...',
                'title' => 'Bar',
            ]
        ]
    ]
]
```
"item" is just an example of a normal field. The important thing is that you have your picture information arrange as a sub-array for each record that you want to import.
You can then use the "link" and "title" fields (or whatever you called them) in the `substructureFields` configuration.

**Comment by Padina14** [comment]
I didn't get your idea to work. It seeems to mie, that there somes differences between import of XML and import of CSV-file, because one XML-"row" can contain a array.

I solved the problem to import several images for one data/row in CSV-file by a customStep. This step added the fields "fal_media" and" fal_media_title" to each recorded record.
If a record should not contain any pictures, the new fields were empty.
     If a record contained one image, then "fal_media" contained the link and" fal_media_title" contained the title of the image.
If a record should contain two or more images, then two or more copies of that record were created.
Each copy of the record contained one image link and the corrospondign image-title.
I used for the import the multipleRow (https://docs.typo3.org/p/cobweb/external_import/5.1/en-us/User/MappingData/Index.html) attribute in the following way:
```
\MyVendor\MyExtension\Utilities\TcaExtendUtility::arrayPush(
    $GLOBALS['TCA']['tx_news_domain_model_news']['columns']['fal_media']['external'],
    \MyVendor\MyExtension\Constants\MyExtension::IMPORT_PROCESS_NEWS_MAIN,
    [
        'field' => 'fal_media',
        'multipleRows' => true,
        'transformations' => [
            20 => [
                'userFunction' => [
                    'class' => \MyVendor\MyExtension\Transformation\ImageTransformation::class,
                    'method' => 'saveImageFromUri',
                    'parameters' => [
                        'storage' => \MyVendor\MyExtension\Utilities\TcaExtendUtility::getSettingsForImport(
                            \MyVendor\MyExtension\Constants\MyExtension::IMPORT_STOARGE_NEWS_IMAGES
                        ), // import Storage from Extensiontemplate of my extension
                        'nameField' => 'fal_media_title',
                        'defaultExtension' => 'jpg',
                    ],
                ],
            ],
        ],
        'children' => [
            'table' => 'sys_file_reference',
            'columns' => [
                'uid_local' => [
                    'field' => 'fal_media',
                ],
                'uid_foreign' => [
                    'field' => '__parent.id__',
                ],
                'title' => [
                    'field' => 'title'
                ],
                'tablenames' => [
                    'value' => 'tx_news_domain_model_news',
                ],
                'fieldname' => [
                    'value' => 'fal_media',
                ],
                'table_local' => [
                    'value' => 'sys_file',
                ],
            ],
            'controlColumnsForUpdate' => 'uid_local, uid_foreign, tablenames, fieldname, table_local',
            'controlColumnsForDelete' => 'uid_foreign, tablenames, fieldname, table_local',
        ],
    ]
); // fal_media < fal_media (extracted from body)
```

**Comment by fsuter** [comment]
It's great that you worked things out finally. It seems that you have pretty much implemented what I was thinking about, but maybe I wasn't clear enough ;-) It's sometimes hard to explain some of the concepts.
