### ISSUE TITLE
Second Import for Categories should not override existing Categorie-relations 

### ISSUE THREAD

**Issue by Padina14** [cobwebch/external_import#188]
I want to import from an old CMS some news into TYPO3. 
I have to import one subset of  categories in a first importstep an a second subset in a second importstep.

The problem. 
External_import deletes the imported relations before it updates the current relations to syscategory. 

How can i solve the problem?

example
The news 'hello World' should contain the category-relation to 'apple' and 'plum'.
The first import-step imports title and first relation
The news 'hello World' contains the category-relation to 'apple'.
The second importstep import the Plum-category
After import the new 'hello world' contains the category-relation to 'plum'   
The third step is with the first-step config.
After Update the news 'hello World' contains the category-relation to 'apple'.
The third step is with the second-step config.
After Update the news 'hello World' contains the category-relation to 'plum'.
  

```
\MyVendor\MyExt\Utilities\TcaExtendUtility::arrayPush(
    $GLOBALS['TCA']['tx_news_domain_model_news']['columns']['categories']['external'],
    \MyVendor\MyExt\Constants\Importmcmdata::IMPORT_PROCESS_NEWS_REL,
    [
        'field' => 'activityfield_id',
        'MM' => [
            'mapping' => [
                'table' => 'sys_category',
                'referenceField' => 'tx_myext_activityfield',
                'default' => '',
            ],
        ],
        'multipleRows' => true,
    ]
);
```

**Comment by fsuter** [comment]
For the second run, you need to set `disabledOperations = 'delete'` in the general configuration, so that the existing relation is not removed.

**Comment by Padina14** [comment]
I thought of that. My CSV-Datas are
```
"news_id","activityfield_id"
61,90
61,89
63,89
64,102
64,118
...
```
It delete  old relations, if I use the following configuration
```
/*********************************************
 *
 * Connector
 * General-Part for import of activities of companys used in new in MCM
 *
 **********************************************/
\MyVendor\MyExtension\Utilities\TcaExtendUtility::arrayPush(
    $GLOBALS['TCA']['tx_news_domain_model_news']['external']['general'],
    \MyVendor\MyExtension\Constants\MyExtension::IMPORT_PROCESS_NEWS_REL,
    [
        'connector' => 'csv', // make dynamical
        'parameters' => [
            'filename' => \MyVendor\MyExtension\Constants\MyExtension::IMPORT_FILES_NEWS_REL,
            'delimiter' => ',',
            'text_qualifier' => '"',
            'skip_rows' => 1,
            'encoding' => 'utf8',
        ],
        'data' => 'array',
        'pid' => (int)\MyVendor\MyExtension\Utilities\TcaExtendUtility::getSettingsForImport(
            \MyVendor\MyExtension\Constants\MyExtension::IMPORT_TS_NEWS_STORAGE
        ),
        'referenceUid' => 'tx_myextension_newsid',
        'priority' => 110,
        'group' => 'LLL:EXT:myextension/Resources/Private/Language/locallang_be.xlf:externalImport.TcaDefinition.news.process.rel.group',
        'disabledOperations' => 'delete,insert',
        'enforcePid' => true,
        'description' => 'LLL:EXT:myextension/Resources/Private/Language/locallang_be.xlf:externalImport.TcaDefinition.news.process.rel.label',
    ]
); // - External/general
\MyVendor\MyExtension\Utilities\TcaExtendUtility::arrayPush(
    $GLOBALS['TCA']['tx_news_domain_model_news']['columns']['tx_myextenson_newsid']['external'],
    \MyVendor\MyExtension\Constants\MyExtension::IMPORT_PROCESS_NEWS_REL,
    [
        // "news_id","activityfield_id"
        'field' => 'news_id',
    ]
);
\MyVendor\MyExtension\Utilities\TcaExtendUtility::arrayPush(
    $GLOBALS['TCA']['tx_news_domain_model_news']['columns']['categories']['external'],
    \MyVendor\MyExtension\Constants\MyExtension::IMPORT_PROCESS_NEWS_REL,
    [
        'field' => 'activityfield_id',
        'MM' => [
            'mapping' => [
                'table' => 'sys_category',
                'referenceField' => 'tx_myextension_activityfield',
                'default' => '',
            ],
        ],
        'multipleRows' => true,
    ]
); // category(tx_myextension_activityfield) < category_id
```

The referenceUid of the other process is related to another column than the process above.
```

\MyVendor\MyExtension\Utilities\TcaExtendUtility::arrayPush(
    $GLOBALS['TCA']['tx_news_domain_model_news']['columns']['categories']['external'],
    \MyVendor\MyExtension\Constants\MyExtension::IMPORT_PROCESS_NEWS_MAIN,
    [
        'field' => 'category_id',
        'MM' => [
            'mapping' => [
                'table' => 'sys_category',
                'referenceField' => 'tx_myextension_category',
                'default' => '',
            ],
        ],
        'multipleRows' => true,
    ]
); // category(tx_myextension_category) < category_id

```

**Comment by fsuter** [comment]
Usage of the `MM` property is not appropriate (and is actually deprecated). Using `multipleRows` is correct, but your mapping information should be:
```
    [
        'field' => 'category_id',
        'transformations' => [
            '10' => [
                'mapping' => [
                    'table' => 'sys_category',
                    'referenceField' => 'tx_myextension_category',
                    'default' => '',
                ],
            ],
        ],
        'multipleRows' => true,
    ]
```
Given your CSV data, this should actually need a single run.

**Comment by Padina14** [comment]
I tried your configuration. 
But the situation is the same. I can only switch between the two states shown in the 

I use actually Typo3 9.5.27 and external_import 5.1.1. (TYPO3-Version Version should not be the problem) 

I will try to find the reason.  
![Bildschirmfoto 2021-05-17 um 10 28 44](https://user-images.githubusercontent.com/63228213/118458359-f5644300-b6fa-11eb-852c-b0a1b449808a.png)
![Bildschirmfoto 2021-05-17 um 10 29 13](https://user-images.githubusercontent.com/63228213/118458367-f6957000-b6fa-11eb-8cc4-532071b3b189.png)

sys_category_record_mm

**Comment by Padina14** [comment]
I think, it ist the problem of the DataMapper. which replaced the old relation by new relations. 
I don't think, that behavior is okay.
I look for a chance, to add missing the existing categorys with a hook to the branch. But the parameter `$id` is missing. OI can't  expand the datas in `$theRecord`;  

```
// see line 206ff. in Cobweb\ExternalImport\Step\StoreDataStep
            if ($isExistingRecord) {
                // First call a pre-processing hook
                if (is_array($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['external_import']['updatePreProcess'])) {
                    foreach ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['external_import']['updatePreProcess'] as $className) {
                        try {
                            $preProcessor = GeneralUtility::makeInstance($className);
                            $theRecord = $preProcessor->processBeforeUpdate($theRecord, $this->importer);
  

```

**Comment by fsuter** [comment]
Yes, you're right, that's the issue, the relationships get replaced. What I still don't understand is why you need to do two runs to import the data. Do you have two (or more) CSV files?

**Comment by Padina14** [comment]
Yes, I have a CSV with a list of new, which contains a uid of a separate list of branding names  (similiar to the TYPO3  N:1-Relation)
And I have a CSV from a mm-file, which contains the uid between the news and the activities (similiar to TYPO3 MM). 
Now the two type of categories should be combined in sys_category. (I know, this ist a anti-solution for database-normalization)

**Comment by fsuter** [comment]
I understand better now. I don't see an easy way out of this. There's clearly no automatic way of preserving the existing relation. One possibility could be to import directly into `sys_category_record_mm` in the second step, but the table has no TCA and the reference count would not be correct.

Another possibility would be to use a custom step to read the existing relation from the database and add it to the list of relations so that it does not get lost.

**Comment by Padina14** [comment]
`Another possibility would be to use a custom step to read the existing relation from the database and add it to the list of relations so that it does not get lost.`
The best position for this is the `updatePreProcess`. But the hook does not transfer the id (see comment above). The argumentt '$id' is missing.

**Comment by fsuter** [comment]
That's because the hook was originally meant to only modify the incoming data. I won't change that, because I'm deprecating hooks in the next major version and replacing them with PSR-14 events, but I will modify the new event so that it receives the id.

I'm not sure, but do you receive the "referenceUid" in the hook? Since this is also unique and saved to the DB, you could use that to fetch the existing record.

**Comment by fsuter** [comment]
https://github.com/cobwebch/external_import/issues/189

**Comment by Padina14** [comment]
The change to signal and slots (PSR-14) is a good idea. 

Cool. 8-) 
Thanks for that hint. I have that information in the variable 'theRecord'. So i can add all 'not-related' category-Ids to the Record. That makes an update of the datas really easy.

**Comment by fsuter** [comment]
Is that issue resolved for you? Can it be closed?

**Comment by Padina14** [comment]
It can be closed.
