### ISSUE TITLE
XML import problems

### ISSUE THREAD

**Issue by Pekkonen** [cobwebch/external_import#202]
I need to import XML file and create IRRE relations in TYPO3 10 and external_import 5.1.1
 ```
<adresse csId="2971551" modified="2021-05-19 10:33:28">
    <adresse_id>2971551</id>
	 <referenz__related_article modified="2021-08-02 09:38:08">
      <_related_article csId="3169040" modified="2021-08-02 09:37:32">
        <id>3169040</id>
        <bezeichnung>bezeichnung1</bezeichnung>
        <url>www.somesite1.com</url>
      </_related_article>
      <_related_article csId="3169041" modified="2021-08-02 09:38:08">
        <id>3169041</id>
        <bezeichnung>bezeichnung2</bezeichnung>
        <url>www.somesite2.com</url>
      </_related_article>
    </referenz__related_article>
</adresse>
```
And we could have many adresse instances.
My goal is get all _related_article items (<bezeichnung>, <url>) and save them into adresse DB with reference by <adresse_id> value.

My TCA is
 ```
$GLOBALS['TCA']['tx_myext_domain_model_set']['external'] = [
    'general' => [
       0 => [
            'connector' => 'feed',
            'parameters' => [
                'uri' => 'fileadmin/Adressen.xml'
            ],
            'data' => 'xml',
            'nodepath' => '//adresse/referenz__related_article/_related_article',
            'referenceUid' => 'importid',
            'priority' => 5000,
            'description' => 'Import related articles',
            'disabledOperations' => 'delete',
            'pid' => '2',
        ],
    ]
];
$GLOBALS['TCA']['tx_myext_domain_model_set']['columns']['importid']['external'] = [
    0 => [
        'field' => 'id',
        'transformations' => [
            10 => [
                'mapping' => [
                    'table' => 'tx_myext_domain_model_set',
                    'referenceField' => 'importid',
                ],
            ]
        ]
    ],
$GLOBALS['TCA']['tx_myext_domain_model_set']['columns']['title']['external'] = [
    0 => [
        'xpath' => 'bezeichnung',
    ]
];

$GLOBALS['TCA']['tx_myext_domain_model_set']['columns']['url']['external'] = [
    0 => [
        'xpath' => 'url',
    ]
];
```
But return first item from XML.

I found similar structure in your test, but something wrong in my case:
https://github.com/cobwebch/externalimport_test/blob/master/Configuration/TCA/tx_externalimporttest_designer.php
https://github.com/cobwebch/externalimport_test/blob/master/Resources/Private/ImportData/Test/Products.xml

Thanks in advance.

**Comment by fsuter** [comment]
The general configuration seems good. When you preview the HandleDataStep, do you have the expected number of records?

I am puzzled by your configuration for the "importid" field. Why are you mapping the table onto itself?

**Comment by Pekkonen** [comment]
> I am puzzled by your configuration for the "importid" field. Why are you mapping the table onto itself?
Yes. I see all that I need.

> I am puzzled by your configuration for the "importid" field. Why are you mapping the table onto itself?
This is obsolete version of code.
Where was 
 ` 'nodetype' => 'adresse',`
Think there is a problem with this? But what exactly?

**Comment by fsuter** [comment]
Well, if the records are new, the mapping will fail and the field will become empty. So if all your fields are empty, in a way, they have the same external id, so only one new record would be created.

This is why I'm asking if you see the expected number of records after the HandleDataStep. They may get lost after the TransformDataStep.

Anyway, you should remove this configuration, which doesn't make sense.

**Comment by Pekkonen** [comment]
Thanks for this idea.
Now I see number of records in DB, but with with wrong ID, this is unique for the each items.
From my example:
<id>3169040</id>
<id>3169041</id>
But I need to link them with one <adresse_id>2971551</id>.

**Comment by fsuter** [comment]
It may not be what you want, but it is not wrong. You need to have this external ID so that External Import can identify those records when importing, to determine which are new, which need to be updated and which deleted.

Relating them to the address is tricky, because the address ID is outside of the scope defined with the `nodepath` property. So in effect, after the HandleDataStep, External Import is blind to it.

In your description you mention that addresses related to articles using a IRRE structure. So you should be able to use the `children` property to import everything in one go (import addresses, with related articles as children), but I must say that I have never used it in such a scenario, only with MM tables, so I'm not sure.

Another solution, which requires some work, could be to use a custom step after the ReadDataStep to parse the XML structure and create a relation between articles and addresses and store it into the `extraData` property of the `Data` object. Then could use another custom step after the HandleDataStep to set that data into the "IRRE parent" field of each record (which you would have declared as an "additionalField" beforehand). In the the TransformDataStep this would then be mapped to the addresses table.

I hope this helps you.

**Comment by fsuter** [comment]
I have found a better solution to your problem :-)

XPath make it possible to select ancestors of a given node and that works totally fine within External Import. In the case of the designers import (from externalimport_test), I have tried with the following code (haven't committed it yet) for a "products" column on the designers table:

```
        'products' => [
            'exclude' => 0,
            'label' => 'Products',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectMultipleSideBySide',
                'foreign_table' => 'tx_externalimporttest_product'
            ],
            'external' => [
                0 => [
                    'xpath' => './ancestor::products/item',
                    'attribute' => 'sku'
                ]
            ]
        ]
```

With this, I get a reference to the product identifier (the "sku" attribute in the XML structure), which I can map to the products table (not in the above example).

**Comment by Pekkonen** [comment]
Hi François!
Thanks for your post!
I've already solved my issue, added new field for the relatedarticles table, and pasted into them data from <adresse_id>.
This is full TCA. Maybe will help someone:
for the related articles
```
$GLOBALS['TCA']['tx_myext_domain_model_relatedarticle']['external'] = [
    'general' => [
       0 => [
            'connector' => 'feed',
            'parameters' => [
                'uri' => 'Adressen.xml'
            ],
            'data' => 'xml',
            'nodepath' => '//adresse/referenz__related_article/_related_article',
            'referenceUid' => 'importid',
            'priority' => 5000,
            'description' => 'Import related articles',
            'disabledOperations' => 'delete',
            'pid' => '2',
        ],
        1 => [
            'connector' => 'feed',
            'parameters' => [
                'uri' => 'Adressen.xml'
            ],
            'data' => 'xml',
            'nodetype' => 'adresse',
            'referenceUid' => 'importid',
            'priority' => 5000,
            'description' => 'Import related articles',
            'disabledOperations' => 'delete',
            'pid' => '2',
        ],
    ]
];


$GLOBALS['TCA']['tx_myext_domain_model_relatedarticle']['columns']['importid']['external'] = [
    0 => [
        'field' => 'id',
    ],
];
$GLOBALS['TCA']['tx_myext_domain_model_relatedarticle']['columns']['title']['external'] = [
    0 => [
        'xpath' => 'bezeichnung',
    ]

];

$GLOBALS['TCA']['tx_myext_domain_model_relatedarticle']['columns']['url']['external'] = [
    0 => [
        'xpath' => 'url',

    ]

];

```
And for the adresse:
```
$GLOBALS['TCA']['tx_myext_domain_model_company']['columns']['relatedarticles']['external'] = [
    0 => [
        'xpath' => 'referenz__related_article/_related_article',
        'substructureFields' => [
            'relatedarticles' => [
                'field' => 'id',
            ]
        ],
        'multipleRows' => true,
        'transformations' => [
            10 => [
                'mapping' => [
                    'table' => 'tx_myext_domain_model_relatedarticle',
                    'referenceField' => 'importid',
                ],
            ]
        ]
    ]
];
```

**Comment by fsuter** [comment]
To be complete, here's the commit corresponding to the idea I had about using the `ancestors` axis in XPath: https://github.com/cobwebch/externalimport_test/commit/4bef700e4ab4394996a78fc97ea4d581dd12b81a
