### ISSUE TITLE
import pid

### ISSUE THREAD

**Issue by stephangrass** [cobwebch/external_import#203]
Hi,
can I set the pid from a field in the import file?

Thanks
Stephan

**Comment by fsuter** [comment]
Yes, you can. You just need to define some minimal TCA for the pid field, which normally doesn't have any. See for example: https://github.com/cobwebch/externalimport_test/blob/0900d7515c1b427928d86653488e2fad446f371a/Configuration/TCA/tx_externalimporttest_product.php#L326

**Comment by stephangrass** [comment]
Thanks
