### ISSUE TITLE
Import without TCA

### ISSUE THREAD

**Issue by DavidBruchmann** [cobwebch/external_import#206]
Is it possible with external_import to import an excel / csv file just as json in a file or common content-table without the need of using TCA?

**Comment by fsuter** [comment]
No, because External Import was designed specifically to map data onto database tables. But it relies on Connector services and you can use those services for your own needs, if you want to keep some standardised way of accessing resources.

**Comment by DavidBruchmann** [comment]
Thanks François, I'll have a look at it.
