### ISSUE TITLE
4.0.0-DEV (Wombat): Path-Problem

### ISSUE THREAD

**Issue by DavidBruchmann** [cobwebch/external_import#21]
Class of own extension not found:
Class 'EXT:my_extension/Classes/Hook/class.myextension_hooks.php:&myextension_hooks' not found

Seems that the path-part "EXT:my_extension" is not translated

**Comment by DavidBruchmann** [comment]
Sorry, this is shown in the scheduler.

**Comment by fsuter** [comment]
OK, will take a look whenever possible, thanks for reporting.

**Comment by fsuter** [comment]
I have removed the wizard in 170c4d97a36b665c2d0e55aab075b4de634ad457. I'm leaving this ticket open for now, if you have other issues to report.

**Comment by fsuter** [comment]
Since you didn't report anything else, I'm closing this issue. I'm very close to making the release.
