### ISSUE TITLE
Error trim() expects parameter 1 to be string, int given after Update to v 6

### ISSUE THREAD

**Issue by stephangrass** [cobwebch/external_import#212]
Hi,
I get the error "trim() expects parameter 1 to be string, int given" in /Users/stephangrass/Documents/_Webs_/thiele.de/typo3/www/typo3conf/ext/external_import/Classes/Step/TransformDataStep.php line 179 in the Transform and StoreDataStep.

I have some fields that can be a string or a number that I want to apply a trim to.
Perhaps one should query in the applyTrim function whether the value is a string?

**Comment by fsuter** [comment]
Indeed, you're right. PHP 8 is not as tolerant as its predecessors.

**Comment by stephangrass** [comment]
Hi Francois,

I hope you are well. Everything went well. You are welcome to send your bill.

Stephan 

Von unterwegs gesendet
