### ISSUE TITLE
TYPO3 Extension Award - Best Documentation 2021

### ISSUE THREAD

**Issue by sypets** [cobwebch/external_import#215]
This issue is for your information only. Please feel free to close

---

**Congratulations**! :sparkles: :tada: 
Your extension has been nominated for the **TYPO3 Extension Award - Best Documentation 2021**.

Three extensions will be chosen as winners by a community vote. In case your extension wins, you will be notified shortly after the voting.

> Voting: November 24 - December 8, 2021 (2 weeks)

In order to vote for an extension:

1. Go to https://extensions.typo3.org and login
2. Click on the “Vote now” button on https://extensions.typo3.org/extension-documentation-award
3. Give 3 points, 2 points and 1 point each for each extension, by clicking on the radio button

Please also look for news on https://typo3.org in the next few days or look on “[Community news](https://typo3.org/project/news/community-1)” for a more detailed description.

Thank you for making your extension available for the TYPO3 community.

Best of luck - and keep inspiring people to share. 

Sybille :smiley:

If you have any questions, please contact me on TYPO3 Slack (`@Sy`).

**Comment by fsuter** [comment]
Feedback from the team, one thing can be improved in the manual:

> Review:
> - guide the user in the horizontal direction by comparing this extension to similar ones of the TER and exposing its benefit: there is also EXT:impexp
>    - see example:
> https://github.com/b13/container#why-did-we-create-another-grid-extension
> - good:
>    - good, clear structure
>    - fluent text is guiding the reader well
>    - good use of formatting
>    - good use of screenshots
>    - mature extension with extensive documentation which is maintained for many years and has seen high activity even throughout this year
>    - using non-screenshot graphics and diagrams to explain database and process details
>    - referencing into official TYPO3 documentation for further details on specific terms
