### ISSUE TITLE
Override specific fields when useColumnIndex is used

### ISSUE THREAD

**Issue by akiessling** [cobwebch/external_import#219]
Hi,

i'm not sure if this is already possible, but i did not find it in the documentation and judging from https://github.com/cobwebch/external_import/blob/master/Classes/Domain/Repository/ConfigurationRepository.php#L69 the setting useColumnIndex forces the config to always be set the value from useColumnIndex

Example: I'm importing data from multilanguage xml files to multilanguage tables. The data is e.g. organized in sibling nodes with an equal structure or with separate fields in the same item node
```
  <items>
    <item>
      <id>1</id>
      <title>foo</title>
      <titleDE>bar</titleDE>
... identical data
    </item>
  </items>
```

I would then like to inherit the config from default, but override the title field for the DE translation.
Also setting static values with a transformation value for sys_language_uid and l10n_parent step does not seem to work for me when i use  useColumnIndex as it always uses the value for the base language.

Code could e.g. look like this, works for me

```
        $useColumnIndex = $configuration['general']['useColumnIndex'] ?? null;
        if (isset($GLOBALS['TCA'][$table]['columns'])) {
            $columnsConfiguration = $GLOBALS['TCA'][$table]['columns'];
            ksort($columnsConfiguration);
            foreach ($columnsConfiguration as $columnName => $columnData) {
                if (isset($columnData['external'][$index])) {
                    $configuration['columns'][$columnName] = $columnData['external'][$index];
                } else if (isset($useColumnIndex, $columnData['external'][$useColumnIndex])) {
                    $configuration['columns'][$columnName] = $columnData['external'][$useColumnIndex];
                }
            }
        }
```

Is this somehow already possible?

**Comment by fsuter** [comment]
No, it is not possible. It could be a nice feature for the future. Thanks for sharing your code.

**Comment by akiessling** [comment]
I can try to prepare a pull request if you like. Are you fine with with _extending_ useColumnIndex? It's rather a kind of fallback: "use base config if specific config is not defined"

**Comment by fsuter** [comment]
Gladly, thanks. I'm not sure what you mean by "extending". Are you talking about the documentation?

**Comment by akiessling** [comment]
What i meant is that this extends the current functionality of useColumnIndex.
I can also prepare a different configuration keyword like e.g. "fallbackColumnIndex" which would be a bit more clear of what it is used for.

**Comment by fsuter** [comment]
I see. I think it is really okay this way. As long as the documentation is updated, I think it's fine.

The very user-friendly thing to do would be in the BE module, when you look up the details about a given configuration, if the "useColumnIndex" could display the list of columns for which an override exists. But I won't block your pull request if you don't do that ;-)

**Comment by akiessling** [comment]
Thank you so much for implementing this! It makes multilanguage imports soooo much easier! I totally forgot about it after working around it and just needed it again! :)
