### ISSUE TITLE
[DOCUMENTATION] add a note about <br /> tags, which could get cut out from imported html

### ISSUE THREAD

**Issue by yb1506** [cobwebch/external_import#221]
I import html into a database field. the values in the external XML had some <br /> tags, but also tags like <ul><li>. When I have imported the data, only the <br /> tags were cut out. the custom RTE config (yaml file) was then the solution:

```
# Allow additional the br tag as allowTagsOutside. the other ones are set default by the core
processing:
  allowTagsOutside: [address, article, aside, blockquote, footer, header, hr, nav, section, div, br]
```
I had to add the br tag to the allowTagsOutside config. this is because the html to imported didn't have a surrounding p or div tag

how to create yaml config: https://docs.typo3.org/c/typo3/cms-rte-ckeditor/main/en-us/Configuration/Examples.html#how-do-i-create-my-own-preset

**Comment by fsuter** [comment]
For reference part of the change is also in another commit (my mistake): https://github.com/cobwebch/external_import/commit/6ec9985e0b74180eedb472355b81e39395b42771
