### ISSUE TITLE
News items didn't get updated

### ISSUE THREAD

**Issue by marexx** [cobwebch/external_import#222]
I Import from a CSV File:

$GLOBALS['TCA']['tx_news_domain_model_news']['external']['general'] = [
        0 => [
            'connector' => 'csv',
            'parameters' => [
                //'filename' => 'typo3conf/ext/bbn_products/Produkte.csv',
                'filename' => 'fileadmin/images/products/raw/Produkte.csv',
                'delimiter' => ";",
                'text_qualifier' => '"',
                'skip_rows' => 1,
                'encoding' => 'latin1'
            ],
            'enforcePid' => true,
            'customSteps' => [
                    [
                            'class' => \Cobweb\ExternalimportTut\Step\FilterWebsiteProducts::class,
                            'position' => 'after:' . \Cobweb\ExternalImport\Step\ReadDataStep::class
                    ]
            ],            
            'data' => 'array',
            'referenceUid' => 'title',
            'priority' => 10,
            'clearCache' => 5,28,29,
            'pid' => 27,
            'group' => 'externalimport_tut',
            'disabledOperations' => '',
            'additionalFields' => 'Sperre am Ausgabedatum,Artikelgruppe,Allergene,Website,Erw. Eigenschaften.Roggenmehl,Erw. Eigenschaften.glutenfrei,Erw. Eigenschaften.hefefrei,Erw. Eigenschaften.lactosefrei,Erw. Eigenschaften.vegan,Erw. Eigenschaften.vegetarisch,Erw. Eigenschaften.Dinkelmehl,Erw. Eigenschaften.Roggenmehl,Erw. Eigenschaften.Weizenmehl,Erw. Eigenschaften.Vollkornmehl,Erw. Eigenschaften.Hefe,Erw. Eigenschaften.Schwein,Erw. Eigenschaften.Rind,Erw. Eigenschaften.Geflügel',
            'description' => 'Import all Products of BBN Schäfer'
        ],

but the items do not get updated. Every time made an import. All Items are created new.
I updated my typo3 from V9 to V10 and the "External_import" is the latest Version.

**Comment by fsuter** [comment]
Can you try the same as your other question and trim the title?

**Comment by marexx** [comment]
no, that doesn't solve the problem. tried it, with 2 different fields.

**Comment by marexx** [comment]
I'm really stuck here :-( my whole TYPO3 update is done, but since i get always dublicated Items i can't finish.
Any idea, why that happens?

**Comment by fsuter** [comment]
Hi. I don't think that this is due to the piece of code you mention.

You're having this issue because the field referenced in the property `referenceUid` ("title" in your example) does not match the existing values. Without knowing your installation or the data you're trying to import, it's impossible to guess why.

Using the preview feature of the BE module, can you try checking one sample record? Make a preview on the `TransformDataStep` and check the value of any record for the "title" field. How does it compare to the "title" field of the matching record in the database? Is it really exactly the same, including opening or trailing spaces?

**Comment by marexx** [comment]
[Readdata](https://kunden.marexx.net/readdata.png)
[transformdata](https://kunden.marexx.net/transformdata.png)

**Comment by fsuter** [comment]
This is weird and there seems to be a misconfiguration. Can you send me by PM (sutfra@gmail.com) the full TCA (or maybe even the whole extension) and at least a sample of the data that you are trying to import?

**Comment by fsuter** [comment]
Handled in private exchanges. For reference in case it can be of use to anyone, the issue was a custom step which created incomplete entries in the external data. These "ghost records" didn't have an external key anymore and thus were duplicated upon each import.
