### ISSUE TITLE
ImageTransformation

### ISSUE THREAD

**Issue by marexx** [cobwebch/external_import#223]
I Want to import the images to fal_media,
they are located in a folder in fileadmin/images/products
but how should the URL be in the CSV so the script can find them?

$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['fal_media']['external'] = [
        0 => [
            'field' => 'Bild',
            'multipleRows' => true,
            'transformations' => [
                10 => [
                    'userFunction' => [
                        'class' => \Cobweb\ExternalImport\Transformation\ImageTransformation::class,
                        'method' => 'saveImageFromUri',
                        'parameters' => [
                            'storage' => '3:product_import',
                            //'nameField' => 'fal_media_title',
                            'defaultExtension' => 'jpg',
                        ],
                    ],
                ],
            ],
            'children' => [
                'table' => 'sys_file_reference',
                'columns' => [
                    'uid_local' => [
                        'field' => 'image' 
                    ],
                    'uid_foreign' => [
                        'field' => '__parent.id__'
                    ],
                    'title' => [
                        'field' => 'title'
                    ],
                    'fieldname' => [
                        'value' => 'Bild'
                    ],
                    'table_local' => [
                        'value' => 'sys_file'
                    ]
                ],
            ],
            'controlColumnsForUpdate' => 'uid_local, uid_foreign, tablenames, fieldname, table_local',
            'controlColumnsForDelete' => 'uid_foreign, tablenames, fieldname, table_local'
        ],
        1 => [
            'field' => 'bannerUrl',
        ]
];

**Comment by marexx** [comment]
Now the result looks like this:
      tx_news_domain_model_news => array(118 items)
         NEW01d623f391711378ddbc => array(15 items)
            categories => '9,14' (4 chars)
            datetime => 1638745200 (integer)
            fal_media => 'NEW5ae14fd2331634a1606d' (23 chars)

**Comment by marexx** [comment]
solved it. the image path must be abolute, not relative.

**Comment by marexx** [comment]
But after each import the image is added to the News, so after 5 imports the News got 5 images.

**Comment by fsuter** [comment]
Sorry for not answering your questions, I'm awfully busy these days. I stumbled upon something similar recently. I can't be sure if that is what is affecting you, but I solved it by applying a "trim" transformation to the URL field. HTH

**Comment by marexx** [comment]
no problem!
do you have an example how to apply it?

**Comment by fsuter** [comment]
Yes, see the example in the latest version of the tutorial: https://docs.typo3.org/p/cobweb/externalimport_tut/4.0/en-us/RssImport/Setup/Index.html

**Comment by EnzephaloN** [comment]
Hello
I also ran into this problem. A trim doen't fix it.

````$GLOBALS['TCA']['tx_cartproducts_domain_model_product_product']['columns']['images']['external'] = [
    0 => [
        'field' => 'bildurl',
        'transformations' => [
            10 => [
                'trim' => true
            ],
            20 => [
                'userFunction' => [
                    'class' => \Cobweb\ExternalImport\Transformation\ImageTransformation::class,
                    'method' => 'saveImageFromUri',
                    'parameters' => [
                        'storage' => '1:imported_images',
                        'nameField' => 'sku',
                        'defaultExtension' => 'jpg'
                    ]
                ]
            ]
        ],
        'children' => [
            'table' => 'sys_file_reference',
            'columns' => [
                'uid_local' => [
                    'field' => 'images',
                ],
                'uid_foreign' => [
                    'field' => '__parent.id__'
                ],
                'title' => [
                    'field' => 'sku'
                ],
                'tablenames' => [
                    'value' => 'tx_cartpoducts_domain_model_product_product'
                ],
                'fieldname' => [
                    'value' => 'images'
                ],
                'table_local' => [
                    'value' => 'sys_file'
                ]
            ],
            'controlColumnsForUpdate' => 'uid_local, uid_foreign, tablenames, fieldname, table_local',
            'controlColumnsForDelete' => 'uid_foreign, tablenames, fieldname, table_local'
        ]
    ]
];
````
Any others ideas?

**Comment by fsuter** [comment]
Not off the top of my head. Is it just the relations (i.e. sys_file_reference entries) that get duplicated or also the files themselves (i.e. sys_file entries and duplicate files on the server?

**Comment by EnzephaloN** [comment]
The files are noc duplicated. The sys_file_referece gets new entries instead of updating them.

**Comment by fsuter** [comment]
Hmm, this is weird indeed, but glad that you found a solution.
