### ISSUE TITLE
Setting $GLOBALS['TYPO3_CONF_VARS']['SYS']['serverTimeZone'] does not exist anymore

### ISSUE THREAD

**Issue by christophlehmann** [cobwebch/external_import#226]
It's used in https://github.com/cobwebch/external_import/blob/2f81c9bed4ff335b0cda9fbfed3d28fc5c9e23bf/Classes/Transformation/DateTimeTransformation.php#L63

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/7.5/Breaking-69930-RemoveOptionServerTimeZone.html

**Comment by fsuter** [comment]
Oh, well spotted, thanks!

That's how you can can see that External Import has been around for a while ;-)

**Comment by fsuter** [comment]
After testing, this parameter is unnecessary and can be removed without replacement.
