### ISSUE TITLE
SQL connector reference one to one relation on import

### ISSUE THREAD

**Issue by lgt** [cobwebch/external_import#230]
Hello,

I'm having the following scenario I already imported my location model and I added the old uid as external_id. Now I import some events which having one to one relations to locations and I would like to reference those in my events Model. How can I fetch the new uid of the location model where external_id is equal with old uid?

Many thanks for Feedbacks

**Comment by fsuter** [comment]
If I understand you correctly, you need to use a mapping transformation: https://docs.typo3.org/p/cobweb/external_import/6.0/en-us/Administration/Mapping/Index.html with the `table` and `referenceField` properties.

**Comment by lgt** [comment]
Thanks! problem solved! I was using wrong the transformation.
