### ISSUE TITLE
Misleading documentation for clearCache config

### ISSUE THREAD

**Issue by akiessling** [cobwebch/external_import#231]
I wanted to configure a cache clearing of the page where my frontend plugins to display the imported data reside and fortunately found an import configuration for that :)
https://docs.typo3.org/p/cobweb/external_import/6.0/en-us/User/Cache/Index.html

But is the example correct? 
```
$GLOBALS['TCA']['tx_news_domain_model_news']['external']['general']['0']['clearCache'] = 'xx,yy';
```

I needed to configure clearCache at the import configuration level to work / show up in the configuration details backend

```
'external' => [
            0 => [
                'clearCache' => '24',
  ...   
```

**Comment by fsuter** [comment]
Hi. As far as I can see, the example is correct. I used that feature myself recently and it works.

If your code sample is indeed what you have typed, then you have missed the `general` index in the configuration array. If your configuration is valid, you should see it appear in the detail view in the backend.

**Comment by akiessling** [comment]
Alright, guess i found it: we hat the config still in 'ctrl', not on top level. Moved it over to the new structure and everything is working fine. Interestingly, the old path still works in 6.0.3

Sorry for the false alert :)

**Comment by fsuter** [comment]
No worries. Great that you solved it!
