### ISSUE TITLE
Save Parent records and relations with one TCA Configuration 

### ISSUE THREAD

**Issue by lgt** [cobwebch/external_import#233]
I have a CSV File which contains 1 to n and mm relations. How would I go for to save with one TCA configuration all the related records.

Here is my example:

One record has a relation to a country model. In this case I have rows from CSV which are containing specific Data for memorial and are related to a Country represented by its name

```
$GLOBALS['TCA']['tx_domain_model_memorial']['columns']['country']['external'] = [
    'memorials' => [
        'field' => 'countryID',  // here I need the ID from from country model. If Country not exists by title than make an insert and return the ID
        /* This is would be a wrong approach in my case while is the opposite what I want
           'children' => [
            'table' => 'tx_domain_model_country',
            'columns' => [
                'title' => [
                    'field' => 'Land'
                ]
            ],
            'controlColumnsForUpdate' => 'title',
            'controlColumnsForDelete' => 'title',
         ]*/
    ]
];
```

Is it possible to save this kind of relations with one Configuration?

**Comment by fsuter** [comment]
I'm not sure that I understand everything that you want to do, but let's get started...

First of all, you mention 1 to n and MM relations. One important thing is that if your import data contains several such relations to different tables, External Import won't be able to handle them in a single configuration (well, there are always ways, but it may be difficult, more difficult than managing several configurations).

If I understand your question correctly, what you want is to create relations to the countries table. So what you want is a mapping transformation: https://docs.typo3.org/p/cobweb/external_import/6.0/en-us/Administration/Mapping/Index.html

If that does not answer your question, I will need more information.

**Comment by lgt** [comment]
Thanks a lot for your Feedback I was able to manage with multiple configurations to import the relational Data. However I have a big problem with the size of database. On each import will increase significantly. Is there any Workaround to control this issue?

**Comment by fsuter** [comment]
I'm guessing that this is due to all the logging happening. External Import has its own log table and - since it relies on the Core's DataHandler - the sys_log table also gets a lot of entries. What I generally do is that I regularly trim those tables using the Scheduler Table Garbage collection task.

You can also configure External Import to avoid logging by the Core, but beware that there are drawbacks to that. See: https://docs.typo3.org/p/cobweb/external_import/6.0/en-us/Configuration/Index.html (bottom of the page).

**Comment by lgt** [comment]
Thanks for Feedback!
