### ISSUE TITLE
fix a static value

### ISSUE THREAD

**Issue by xbouillet** [cobwebch/external_import#245]
Hello,

I use TYPO3 9 with external import 5.1.1

I manage to import my data from an xml. It works.
Ex: 
`$GLOBALS['TCA']['tx_eannuaires_domain_model_fiche']['columns']['title']['external'][0] = array('field' => 'name');`

I try to use a static value :

here is my code:
`$GLOBALS['TCA']['tx_eannuaires_domain_model_fiche']['columns']['typeelement']['external'][0]['transformation']['value']  =  '2';`

It's doesnt work, this returns part of the XML to me.

I tried a lot of syntax but I can't just fix a static value.

any help plase?

Thanks a lot :):)

**Comment by xbouillet** [comment]
It was transformation with a s and not transformation

**Comment by fsuter** [comment]
Great that you could work it out!
