### ISSUE TITLE
Trigger a synchronization from extern 

### ISSUE THREAD

**Issue by bastikoe** [cobwebch/external_import#253]
Hello, 

first of all many thanks for this great extension!

With your extension I want to import data from a self-programmed external web application. The data is provided via an API as json. This works quite well via your BE module, as well as via the scheduler. 

But now I want to be able to "start / trigger" a synchronization from my web application. My web app sends a request to Typo3, where this request is then processed and the synchronization is started. 

My idea is to write a small middleware in Typo3, which accepts this request and then calls the importer accordingly. However, I am now running into the problem that there is no BE user logged in in this scenario, which is why the importer aborts accordingly. 

Does anyone have an idea how I could work around this or does anyone have an alternative approach? 

Thanks

**Comment by fsuter** [comment]
Hi. You will need to simulate a BE user in your middleware and set it as admin. To ensure security, unset that user before your script returns the response.
You could also set up a non-admin user, which matches an existing user in the database. It is safer but it requires that this user has the proper rights, and I would imagine that your API call is already protected by other means.

**Comment by bastikoe** [comment]
Thank you for the answer. I already had something like that in mind, but I can't get any further with it. Do you have a resource where I can learn about the topic "simulate users in Typo3"?

**Comment by fsuter** [comment]
You can look at what is done in workspaces, for the preview mechanism: `\TYPO3\CMS\Workspaces\Middleware\WorkspacePreview::initializePreviewUser()`. You would then assign the user to `GLOBALS['BE_USER']->user`.

This is untested, but it should get you going. HTH

**Comment by bastikoe** [comment]
Thanks a lot! I will take a look at this. Thanks for your input.
