### ISSUE TITLE
[FEATURE REQUEST] define in which order columns should get processed/transformed

### ISSUE THREAD

**Issue by oliverbeck-dev** [cobwebch/external_import#255]
Hi,

first I want to thank you for this extension, great work!

Is it correct that columns get processed in alphabetical order? I'm still not really sure about that. Regardless I would like if it's possible to take control of that order somehow. The reason is, I have some columns which depend on others and I need the transformed data of e.g "columnB" in "columnA"

Kind regards, oliver

**Comment by fsuter** [comment]
Hi. Yes, it is correct that columns are processed in alphabetical order and I agree that this is sometimes a problem. I have generally solved this by using custom steps, but it would indeed be a nice feature to have a known ordering for columns processing.
