### ISSUE TITLE
 Failure in documentation of transformations configuration

### ISSUE THREAD

**Issue by m10a** [cobwebch/external_import#258]
You have a failure in your documentation: In 
[https://github.com/cobwebch/external_import/blob/master/Documentation/Administration/Transformations/Index.rst](url)

It should be 
`'class' => \Cobweb\ExternalImport\Transformations\DateTimeTransformation::class,` 

instead of 

`'class' => \Cobweb\ExternalImport\Task\DateTimeTransformation::class,` 

in line 148

**Comment by fsuter** [comment]
Thanks for spotting it. I'll fix it in the next release.
