### ISSUE TITLE
After installation of version 6.2.0 got an ParseError in BE and FE (Typo3 10.4.34)

### ISSUE THREAD

**Issue by macbombastic** [cobwebch/external_import#262]
ParseError:

syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)
in /var/www/html/public/typo3conf/ext/external_import/Classes/Domain/Model/Dto/ChildrenSorting.php line 26

Typo3 version: 10.4.34
Composer version: 2.5.1
PHP version: 7.2.34

Fallback to 6.1.1 solved the issue in the new feature.

**Comment by fsuter** [comment]
Sorry, there's indeed an issue with PHP 7.2 compatibility. I'll issue a bug fix release.
