### ISSUE TITLE
Faeture Request: Add option to only generate slugs on insert

### ISSUE THREAD

**Issue by cbaur** [cobwebch/external_import#277]
When using the `updateSlugs` option in the general configuration, it is probably not intended to update the slug of a record on every import. Consider the following scenario:

Records are retrieved from an API on a regular basis, slugs are generated from a combination of record id and title. The title of a record might change over time. In this case, the slug of the record would change as well, leading to unwanted 404s for the old URLs.

In my opinion, the best option would be to let the integrator choose if the slugs should be updated on every import or only on insert, maybe like so:

```
'updateSlugs' => true // updates slugs on every import
'updateSlugs' => 'onInsert' // generates slug on first import
```

I think the required information for implementing this should already be available in the StoreDataStep class.

**Comment by fsuter** [comment]
Hi Christian. Maybe I misunderstand your need, but External Import already works that way. When a new record is inserted, the TYPO3 Core Engine (not External Import) automatically generates a slug. If the `updateSlugs` flag is not set (which is the default), the slugs are **not** updated on every import.

**Comment by cbaur** [comment]
Hi Francois,
thanks for the quick reply. Glad to hear that. I think I've experienced an empty slug field due to the fact that I've added the slug field AFTER importing records. Thus, technically I always just updated the records of course. Thanks again for the clarification!
