### ISSUE TITLE
[Question] import of localized record, connect records for localization

### ISSUE THREAD

**Issue by medarob** [cobwebch/external_import#294]
Use case:

I have one JSON or XML file and inside are multiple datasets/records in German and English.
For example, two records:
Record 1 is German
Record 2 is English

Record 2 is a direct translation of Record 1. There is no dependency.

In TYPO3 I would like to have both connected, meaning, the English record should be a localized record of the German version.
It would be the same as I would have the German record in TYPO3, then click the localize/translate button to create a localized version of the record.

Is that possible with the import tool, to import the German version and then automatically add a localized version and fill that one with the data from the English record? Or I add both records but have to specify somewhere that Record 2 is a localization of Record 1.

**Comment by fsuter** [comment]
I would try this the following way: map the field containing the external key both to the "uid" column and to the "l10n_parent" column. After the `HandleDataStep`, introduce a custom step where you set the "l10n_parent" column to null for the records in German. Use a mapping transformation to map the "l10n_parent" field onto the table itself.

There could be other ways to do this, but I think this is the simplest. If you have a field identifying the language in each row, there may be a simpler way.

**Comment by fsuter** [comment]
I'm assuming that you have resolved this situation since then and will close this issue. Feel free to reopen it if that is not the case.
