### ISSUE TITLE
SQL Error message missing information

### ISSUE THREAD

**Issue by dvdmlln** [cobwebch/external_import#297]
Hi,

I tried to import some data from a csv file containing decimal values with a comma delimiter which led to an SQL error, because the SQL field with type decimal only accepts a dot delimiter.

The data import module showed the following (not very helpful) error:

![Screenshot 2023-09-28 091355](https://github.com/cobwebch/external_import/assets/64189384/5bda8ca5-0987-4808-8776-47b5f42fdad4)

**Comment by fsuter** [comment]
Hi. Indeed I discovered just this week that the format of the `sys_log` table had changed, with data being stored in JSON format instead of a serialized array. I will need to adapt the reporting made by External Import.
