### ISSUE TITLE
PHP8: Warning: Undefined variable $label

### ISSUE THREAD

**Issue by dogawaf** [cobwebch/external_import#306]
I got this error sometimes when an error occurs in DataHandler processing.

`Message: PHP Warning: Undefined variable $label in /var/www/html/web/typo3conf/ext/external_import/Classes/Step/StoreDataStep.php line 1054`

external_import v7.1.2
php 8.0

**Comment by fsuter** [comment]
Thanks for reporting. This is a regression introduced by 45ecd02.
