### ISSUE TITLE
Given select field item list was not found

### ISSUE THREAD

**Issue by marexx** [cobwebch/external_import#321]
Hi,

i installed external_import 7.2.4 on typo3 12.4.14

i get the error:
`Given select field item list was not found.

in /html/typo3/typo3_src-12.4.14/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 438
        }
        if (!isset($GLOBALS['TCA'][$table]['columns'][$field]['config']['items'])
            || !is_array($GLOBALS['TCA'][$table]['columns'][$field]['config']['items'])
        ) {
            throw new \RuntimeException('Given select field item list was not found.', 1303237468);
        }
        // Make sure item keys are integers
        $GLOBALS['TCA'][$table]['columns'][$field]['config']['items'] = array_values($GLOBALS['TCA'][$table]['columns'][$field]['config']['items']);
        if ($relativePosition !== '') {
at TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTcaSelectItem('sys_reaction', 'reaction_type', array('label' => 'LLL:EXT:external_import/Resources/Private/Language/locallang_db.xlf:sys_reaction.reaction_type.import_external_data', 'value' => 'import-external-data', 'icon' => 'tx_external_import-reaction-import'))
in /html/typo3/typo3conf/ext/external_import/Configuration/TCA/Overrides/sys_reaction.php line 8
use Cobweb\ExternalImport\Utility\CompatibilityUtility;
use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;

if (CompatibilityUtility::isV12()) {
    ExtensionManagementUtility::addTcaSelectItem(
        'sys_reaction',
        'reaction_type',
        [
            'label' => ImportReaction::getDescription(),`

can you help me out?

I know you do not really suppoert non-composer installations, but this doesn't seems to be a composer problem?

**Comment by fsuter** [comment]
Hi, have you installed system extension "reactions"?

It is actually required for v12, but since I kept external_import compatible also with v11, I couldn't add "reactions" as an explicit requirement. I know that it makes a mess, but I haven't found a better solution so far. This issue is being discussed here: https://github.com/cobwebch/external_import/issues/298

**Comment by fsuter** [comment]
Usage of the compatibility utility class has been replaced in https://github.com/cobwebch/external_import/commit/9001d5e7b9a04934e99e50a2e542599d349ead66

I will soon release a new minor version. I'll keep you posted and you can test whether this still happens or not.
