### ISSUE TITLE
Output to console with importer->debug()

### ISSUE THREAD

**Issue by vk-chaertl** [cobwebch/external_import#323]
Hello there,

This is probably an embarrassing question, but here we go: I thought I would output messages to console when I use 

`$this->importer->debug(
                sprintf(
                    'Filename: %s',
                    $fileName
                ),
                4
            );`

However, this doesn't seem to work for some reason. I do get other output, namely the general status messages and also the item list, but not the filename that I am seeking above.
I'm in a custom image transformation with both your transformer and the importer imported:

`use Cobweb\ExternalImport\Transformation\ImageTransformation as BaseImageTransformation;
use Cobweb\ExternalImport\Importer;`

Any clue what I'm doing wrong?

EDIT: Typo3 v12.4.15, external import v7.2.4

**Comment by fsuter** [comment]
Hi. You're doing nothing wrong. However calls to `debug()` actually go to the TYPO3 logging system, so you need to configure that. Here is the core documentation about that feature: https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Logging/Index.html

**Comment by vk-chaertl** [comment]
A thousand thanks, you're the best, as always!
