### ISSUE TITLE
arrayPath 'No configuration.' 

### ISSUE THREAD

**Issue by jblechinger** [cobwebch/external_import#330]
Hello, i trie to get the country from the following xml:

nodetype is set to 'jobPublication'

```
<list>
    <jobPublication>
        <id>1234</id>
        <jobOpening>
            <locations>
                <location>
                    <country>
                        <name>Deutschland</name>
                        <isoA2>DE</isoA2>
                    </country>
                </location>
            </locations>
        </jobOpening>
    </jobPublication>
</list>
```

I tried a lot of different variations of the following 'arrayPath':

```
        'country' => [
            'exclude' => true,
            'label' => 'Country',
            'config' => [
                'type' => 'input',
                'size' => 90,
                'eval' => 'trim',
            ],
            'external' => [
                0 => [
                    'arrayPath' => 'jobOpening/locations/location/country/name',
                ]
            ]
        ],

```

In the 'column Mapping' tab of the backend it says:

![image](https://github.com/cobwebch/external_import/assets/23359626/5483f3b0-c55a-4ecd-9f5d-c30266e0400b)

Can someone please help me go extract nested xml Data?

**Comment by fsuter** [comment]
Hi. You can't use `arrayPath` here, because you're in a XML structure. You need to use `xpath` instead (https://docs.typo3.org/p/cobweb/external_import/7.2/en-us/Administration/Columns/Index.html#xpath).

**Comment by jblechinger** [comment]
Thanks for the quick help :)
