### ISSUE TITLE
Removing MM relations does not work

### ISSUE THREAD

**Issue by akiessling** [cobwebch/external_import#34]
I might have found a bug with updating MM relations. My config for the field looks like this:

```
$GLOBALS['TCA']['my_table']['columns']['my_field']['external'] = [
    0 => [
        'field' => 'field_from_xml',
            'mapping' => [
                'table' => 'my_other_table',
                'reference_field' => 'importer_title',
                'multipleValuesSeparator' => ';'
            ]
    ]
];
```
So in the my_other_table, i have records with a field `importer_title` and need to match a semicolon separated list of keys and build up relations. The TCA for the field is just a regular multiselect with an mm table
```
'config' => [
    'type' => 'select',
    'renderType' => 'selectMultipleSideBySide',
    'foreign_table' => 'my_other_table',
    'MM' => 'my_relation_table_mm',
```

TBH, the MM config in the documentation is a bit confusing, since i use the config from https://docs.typo3.org/typo3cms/extensions/external_import/Administration/Mapping/Index.html, because the DataHandler just resolves the comma separated list of values for saving the relations. I had a look at  https://docs.typo3.org/typo3cms/extensions/external_import/Administration/MmRelations/Index.html, but `multipleValuesSeparator` only works in the mapData method and i think that config is not intended for my usecase.

The actual problem:
Step 1: import data, create relations
Step 2: add a new relation value -> mm relations are updated
Step 3: remove relations (not all) -> mm relations are updated
Step 4: remove all relations -> field is skipped for the import in https://github.com/cobwebch/external_import/blame/master/Classes/Importer.php#L893

If i just use the empty value (`$records[$i][$columnName] = ''`) instead of unsetting the field, it seems to work properly.

**Comment by fsuter** [comment]
I'm not sure that I fully understand what your issue is. Especially I don't understand what the 4 steps you list above correspond to. Could you try to clarify please?

However I agree that the `empty()` check may be a bit aggressive. Testing emptiness is always tricky.

**Comment by akiessling** [comment]
Hi Francois,
The 4 Steps are how i discovered the problem. To summarize: adding and removing values from  an mm relation of an existing record work, but if the mapping does not return any results and thus ALL relations should be removed, the unsetting from Importer.php#L893 kicks in and the field / mm relations are skipped during the update process --> the relations from the previous run are still in the database.

The empty check for the mm relation should be fine IMHO, DataHandler expects a comma separated list of values. If that is empty, there should be no relations.

**Comment by fsuter** [comment]
Thank you for rephrasing your discovery. It is much clearer now :-)

I can't guarantee you when I will have time to work on this bug, though. I'm very busy these days and the time I spend on External Import is mostly dedicated to rolling out version 4.0.

BTW which TYPO3 version are you running? If I correct this bug, it will likely be for External Import 4.0 and not older versions, which means it will require TYPO3 7 or 8.

**Comment by fsuter** [comment]
Your proposed solution has indeed quite some side effects. I was able to reach a better solution by using the recently introduced "default" property for "mapping" configurations. With this, it is possible to set the default value when the mapping does not match at all. This value is applied instead of the item being unset. Setting an empty string as a default value will do the job of telling the DataHandler to clean up existing MM relations.

See the referenced commit.

**Comment by fsuter** [comment]
If you can't upgrade to the 4.0 version when it's releases (which should be soon now), just keep your local fix if it hasn't side effects for you.
