### ISSUE TITLE
Combine two fields

### ISSUE THREAD

**Issue by Chriz74** [cobwebch/external_import#340]
I have a JSON-File with two different fields for Categories. I am importing to news an as i understand from the docs, the mm-relation is automaticly adjusted, when you serve a Comma-separated Category-List.
So my JSON-File is as following:
```json
{
  "id": 150,
  "departmentAlternative": {
    "id": 1092,
    "key": "78",
    "title": "CategoryOne"
  },
  "department": {
    "id": 1113,
    "key": "219",
    "title": "CategoryTwo"
  }
} 
```

So i thought i can handle the mapping in a custom table-field with:
```php
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['tx_myext_category']['external'] = [
    0 => [
        'field' => 'department',
        'arrayPath' => 'department/title',
        'transformations' => [
            10 => [
                'trim' => true,
            ],
        ],
    ],
    1 => [
        'field' => 'departmentAlternative',
        'arrayPath' => 'departmentAlternative/title',
        'transformations' => [
            10 => [
                'trim' => true,
            ],
        ],
    ],
];
```

but i get only one category .... i think the best would be a comma-separated list in the field to map it to the categories, but why am i getting only one category?
(TYPO3 v11)
Thx ;)

**Comment by fsuter** [comment]
Hi. You can't do it this way. Each import configuration is keyed to one index. In your case, by using `0` and `1`, you are creating 2 import configurations. Assuming that you general configuration uses index `0`, the column configuration with index `1` would just be ignored. Hence a single category.

There's no direct way to achieve what you want. You need two steps:

1. use an additional field to map the `departmentAlternative/title` field
2. a transformation with a user function to concatenate `department` with `departmentAlternative`.

HTH

**Comment by fsuter** [comment]
Is this solved for you?

**Comment by Chriz74** [comment]
Thx for your reply! I am hanging in the userFunc ;)
But i think this can be closed for now.

**Comment by fsuter** [comment]
Thanks for your feedback.
