### ISSUE TITLE
Import images from secured path

### ISSUE THREAD

**Issue by EnzephaloN** [cobwebch/external_import#354]
Hello

Is it possible to import images from path, which is secured by[ EXT:secure_downloads](https://github.com/Leuchtfeuer/typo3-secure-downloads)? If its possible, how to write TCA-part for this? This path denies direct access by htaccess.

Actually I have this configuration:
````
$GLOBALS['TCA']['tx_cartproducts_domain_model_product_product']['columns']['images']['external'] = [
    0 => [
        'field' => 'bildurl',
        'transformations' => [
            10 => [
                'trim' => true
            ],
            20 => [
                'userFunction' => [
                    'class' => \Cobweb\ExternalImport\Transformation\ImageTransformation::class,
                    'method' => 'saveImageFromUri',
                    'parameters' => [
                        'storage' => '1:productimport',
                        'nameField' => 'sku',
                        'defaultExtension' => 'jpg'
                    ]
                ]
            ]
        ],
        'children' => [
            'table' => 'sys_file_reference',
            'columns' => [
                'uid_local' => [
                    'field' => 'images',
                ],
                'uid_foreign' => [
                    'field' => '__parent.id__'
                ],
                'title' => [
                    'field' => 'sku'
                ],
                'tablenames' => [
                    'value' => 'tx_cartproducts_domain_model_product_product'
                ],
                'fieldname' => [
                    'value' => 'image'
                ],
                'table_local' => [
                    'value' => 'sys_file'
                ]
            ],
            'controlColumnsForUpdate' => 'uid_local, uid_foreign, tablenames, fieldname, table_local',
            'controlColumnsForDelete' => 'uid_foreign, tablenames, fieldname, table_local'
        ]
    ]
];

````

I think saveImagesFrom Uri isn't the best method to do this, maybe there is a better way?

Best regards
EnzephaloN

**Comment by fsuter** [comment]
Hi. This will definitely not work as is with "saveImageFromUri". I'm not sure how I would proceed with that myself, but one way I can think of is to create your own version of said method and add to it a process of authenticating with the TYPO3 frontend that you are querying. Then you should be able to use the secured URIs provided by secure_downloads to retrieve the file. Or maybe there's some event or hook in secure_downloads which would enable you to bypass the usual process using some other method to secure the exchange (it could just be the IP address, which is not foolproof, or an exchange of tokens).

Anyway, it's not something that can be provided out of the box by External Import, as it is a very specific situation. Indeed the ImageTransformation class - although quite useful as is - is also meant to be an inspiration or code base for more complex scenarios.
