### ISSUE TITLE
Handling JSON sub-arrays

### ISSUE THREAD

**Issue by AstCommodore** [cobwebch/external_import#51]
Hello there,

I'm trying to import and JSON file to fe_users table – everything works well, but I got an external field "address" which is a array:

`Array ( [street] => Dummy Street [number] => 1 [zip] => 83700 [city] => Dummy City [lat] => 12.345678 [lon] => 12.345678 )`

To map the data for fe_users I created some simple userFunc:

`public function getCity($record, $index, $params)
    {
        return $record['address']['city'];
    }` 

The config in TCA looks like this:

`$GLOBALS['TCA']['fe_users']['columns']['zip']['external'] = array(
    0 => array(
        'field' => 'address',
        'transformations' => array(
            10 => array(
                'userFunc' => array(
                    'class' => \Vendor\EXT\Transformation\FieldTransformation::class,
                    'method' => 'getZip'
                )
            )
        )
    )
);`

This is working so far! But if I add the configuration for fe_users.address the fields zip, city, lat and lon aren't imported, because $record['address'] is now set to the value assembled by 

`public function getAddress($record, $index, $params)
    {
        return $record['address']['street'] . ' ' . $record['address']['number'];
    }`

How could I solve this conflict? Could I access an array sub-key more simple?
Thanks for response!

Get stuff at all! Saved my life many times. Thanks for your great work.

**Comment by fsuter** [comment]
With what is available currently, I would use the new custom steps feature to solve your issue. If you register a custom step to execute after the "read data" step, you will have access to all records, on which you can loop. You could then add fields the each row with the "sub-data" from the address field. These extra fields should map nicely to the "field" property defined in the TCA.

However I agree that accessing an array sub-key would be more simple. It is currently not an available feature, but I'm guessing that it could be implemented quite simply using the TYPO3 API `\TYPO3\CMS\Core\Utility\ArrayUtility::getValueByPath()`. But I can't promise when I would have time to implement this. So the first solution is probably the best.

I'm glad you find this extension useful. It's my personal favorite among my work ^_^

HTH

**Comment by AstCommodore** [comment]
Thank you for the fast response! 
My 'time-saving' work-arround is using another field for the 'address' – not really fine, so maybe I will use your first solution.
