### ISSUE TITLE
composer.json dependencies

### ISSUE THREAD

**Issue by presedo** [cobwebch/external_import#56]
As the ext_emconf.php says the extension requires svconnector, composer.json should require it too
` "cobweb/svconnector" : "3.2.3"`
otherwise external_import cannot be installed from the extension manager in composer mode, without adding cobweb/svconnector in the project's composer.json

**Comment by fsuter** [comment]
Actually the solution is the contrary: the dependency should be removed from ext_emconf.php, as External Import be used as API and this without connector services.

**Comment by fsuter** [comment]
Although it's kind of embarrassing to remove this dependency, because it is then impossible to set a version requirement on svconnector if it is to work properly with external_import...
