### ISSUE TITLE
Transformation return value is reduced to 0 or 1 on integer field

### ISSUE THREAD

**Issue by yeldiRium** [cobwebch/external_import#60]
Hi!

I'm using the Extension for the first time and came across the following Problem:

Ich have two Domain Models, called Lodge and ComfortCategory.
These are connected with a one to many Relationship via TCA and Extbase.
I'm trying to import Data into the ComfortCategory table. The data source for the Lodge table does not work yet, but the table contains current data.

Basically I want to replace the old content of the ComfortCategory table with new content from an external source and make sure, that afterwards all relationships to the old data in the Lodge table are still working.

Now ComfortCategory only has a back-referencing field containing the number of Lodges linking to it, as is standard in Extbase one to many relationships.

Setting this field's value with the 'mapping' configuration has not worked for me, since the resulting value was not the number of incoming links, but always 1. Thus I tried it with a userFunc myself:

The TCA for the field looks like this:
```php
...
'lodges' => [
    'exclude' => true,
    'label' => 'LLL:EXT:my_extension/Resources/Private/Language/locallang_db.xlf:comfortcategory.lodges',
    'config' => [
        'type' => 'inline',
        'foreign_table' => 'tx_myextension_domain_model_lodge',
        'foreign_field' => 'comfortcategory',
        'maxitems' => 9999,
        'appearance' => [
            'collapseAll' => 0,
            'levelLinksPosition' => 'top',
            'showSynchronizationLink' => 1,
            'showPossibleLocalizationRecords' => 1,
            'showAllLocalizationLink' => 1
        ],
    ],
    'external' => [
        0 => [
            'field' => 'Id',
            'transformations' => [
                10 => [
                    'userFunc' => [
                        'class' => \CompanyNamespace\CountReferenceTransformation::class,
                        'method' => 'countComfortToLodges'
                    ]
                ]
            ]
        ]
    ]
],
...
```

and the corresponding Transformation class looks like this:

```php
class CountReferenceTransformation implements SingletonInterface
{

    /**
     * @param array $record The full record that is being transformed
     * @param string $index The index of the field to transform
     * @return integer Number of incoming references from Lodges to the given
     *  ComfortCategory record
     */
    function countComfortToLodges($record, $index)
    {
        return 7;
    }
}
```

Last but not least, the column is defined as
```
lodges int(11) unsigned DEFAULT '0' NOT NULL,
```

Obviously my Transformation is not finished yet, since it always returns the value 7. 
Thing is, that the value in the database is always 1.
If I return 0 or anything that is not an integer in my transformation userFunc, the value in the db will be 0.
If I return any valid integer, it is set to 1.

Am I missing something here?
Is this even a problem with external_import?

Thanks in advance and kind regards,
yeldiR

P.S.: The external configuration for the table is:
```php
'external' => [
    0 => [
        'connector' => 'json',
        'parameters' => [
            'uri' => 'https://obviouslycensored.source/querystring',
            'encoding' => 'utf-8'
        ],
        'data' => 'array',
        'referenceUid' => 'external_uid',
        'priority' => 1,
        'pid' => 189,
        'minimumRecords' => 10
    ]
],
```

**Comment by fsuter** [comment]
Hi. Unfortunately, you can't achieve what you want this way. What happens with your user function is that you set the value of the "lodges" field to 7. But the field definition is that it is a relation to the lodges table. So in fact what your code is saying is that the comfort category is actually related with the lodge having uid = 7. Which means a single relationship, hence the resulting 1 in the database.

What you need to do is assemble a comma-separated list of lodges for each comfort category and return that as a value in your user function. I just have a small doubt here, because I never fully tested External Import with IRRE-type relations, but it should work.

**Comment by yeldiRium** [comment]
That makes a lot of sense! Interesting, that the id list would be matched against its references before writing to the database.
Hopefully I'll get to try it out tomorrow and report back on my results.

Thank you for the insight.

**Comment by fsuter** [comment]
Maybe what helps you understand this "weirdness" better is that the structure that Extenal Import assembles is not feeding directly some method that writes to the DB. Instead it assembles a structure handled by TYPO3's DataHandler class. Hence some peculiarities ;-)

**Comment by yeldiRium** [comment]
I got it working.
Thank you very much for helping me understand.

I'm not generating a comma separated list of all connected Lodges and it is parsed correctly. The field in the db now contains the number of connected Lodges.

**Comment by fsuter** [comment]
Excellent, great news!
