### ISSUE TITLE
Wrong condition?

### ISSUE THREAD

**Issue by webian** [cobwebch/external_import#74]
Hi @fsuter,
maybe there's a wrong condition:
https://github.com/cobwebch/external_import/blob/6b8b059bed30179a3b59f444b80a0c1bb69ac629/Classes/Utility/MappingUtility.php#L215

because before:
https://github.com/cobwebch/external_import/blob/6b8b059bed30179a3b59f444b80a0c1bb69ac629/Classes/Utility/MappingUtility.php#L189

So `$mappingData[$referenceField]` will always be NULL.

**Comment by fsuter** [comment]
Hmm, that looks wrong indeed. I need to introduce a test which covers this.
