### ISSUE TITLE
Risky comparison between pid

### ISSUE THREAD

**Issue by webian** [cobwebch/external_import#81]
https://github.com/cobwebch/external_import/blob/29f957f14947bc8316ce86d7d0048aa4ec4cfa5e/Classes/Step/StoreDataStep.php#L197

I think that this comparison between pid must be forced as int or else in many cases will compare string and integer and, even if pid is practically equal, the page results to be to move even if it isn't.

Line should be:
`if (array_key_exists('pid', $theRecord) && (int)$theRecord['pid'] !== (int)$currentPids[$externalUid]) {`

**Comment by fsuter** [comment]
You're right, I have improved this, considering that the existing pids are integers (the PDO layer takes care of casting properly when retrieving from the database).

Thanks for taking such a close look at the code!
