### ISSUE TITLE
$rootLevelFlag could be true

### ISSUE THREAD

**Issue by webian** [cobwebch/external_import#82]
Hi @fsuter 
I'm importing external records to table `sys_file` and its `rootLevel` is `true` so I guess that this condition
https://github.com/cobwebch/external_import/blob/78a0e25a172b8bd68256f713106637d588858345/Classes/Validator/ControlConfigurationValidator.php#L281
should consider it and become:
`$rootLevelFlag === -1 || $rootLevelFlag === 1 || $rootLevelFlag`
what do you think?

**Comment by fsuter** [comment]
I checked the TYPO3 Core and `rootLevel` is indeed defined as `true` in TYPO3 8, and corrected to `1` in TYPO3 9. Still it must be taken into account, so I will add your proposal.
