### ISSUE TITLE
Abort import if exception

### ISSUE THREAD

**Issue by webian** [cobwebch/external_import#83]
Hi @fsuter,
actually the import catches exceptions and logs the error (if debug enabled) while applying user functions:
https://github.com/cobwebch/external_import/blob/78a0e25a172b8bd68256f713106637d588858345/Classes/Step/TransformDataStep.php#L217
but the import goes on.
Shouldn't it abort?

**Comment by fsuter** [comment]
This is not an easy one. There are many exceptions which can happen and my experience is that not catching anything can interrupt the import for a single record that has an inappropriate value.

It would be great to be able to tell things apart based on the exception, but there can really be a huge variety of exceptions happening especially in that step.

Maybe one solution could be to introduce an exception like `CriticalImportFailureException`, which developers could throw in their code (for example, their user functions, which are called in this step). This particular exception would cause the process to abort, and the others not.

How does that sound? Does it make sense in your particular case?

**Comment by webian** [comment]
I think that's a great idea that external_import could handle that `CriticalImportFailureException`!

**Comment by fsuter** [comment]
The final name for the exception is `\Cobweb\ExternalImport\Exception\CriticalFailureException`.
