### ISSUE TITLE
Combine fields to import to one Field

### ISSUE THREAD

**Issue by marexx** [cobwebch/external_import#87]
Hi,
I'm trying to import Data from a CSV to tx_news. it Works fine. I've just a problem with the categories.
I've one Cat that looks like that:
Artikelgruppe => 'Brötchen' (9 chars)
with the Mapping it works fine. But i've other Categories in a different field:
Allergene => 'GLUTEN, MILCH, SESAMSAMEN' (25 chars).
each of the words is a different category. How can I add this  too? I tried it that way:

$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['categories']['external'] = [
        0 => [
            'field' => 'Artikelgruppe',
            'MM' => array(
                'mapping' => array(
                    'valueMap' => array (
                        'Brötchen' => 9,
                        'Bäckersnacks' => 10,
                        'Körnerbrötchen' => 11,
                        'Brote' => 17
                    ),
                    'table' => 'tx_bbnproducts_domain_model_category',
                    'multipleValuesSeparator' => ','
                ),
            ),
        ],
        1 => [
            'field' => 'Allergene',
            'MM' => array(
                'mapping' => array(
                    'valueMap' => array (
                        'GLUTEN' => 14,
                        'SESAMSAMEN' => 15,
                        'MILCH' => 16
                    ),
                    'table' => 'tx_bbnproducts_domain_model_category',
                    'multipleValuesSeparator' => ','
                ),
            ),
        ]        
];

But that just works for the first one.

**Comment by fsuter** [comment]
At first sight, this looks fine. I suppose that the difference in behaviour is due to the first field having a single value, where the second one has several. Is that indeed always the case?

When I look at the various samples that I use for testing, I see that I have no test of the `MM` and `multipleValuesSeparator` combo, so maybe this use case is buggy. I would need to do some testing on my side to be able to assess whether it is a bug of External Import or some misconfiguration on your part. It may take me a couple of days to find the time to do so...

**Comment by marexx** [comment]
OK, thanks. I think i don't need the MM, because i want to import it into tx_news.

`$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['categories']['external'] = [
        0 => [
            'field' => 'Artikelgruppe',
            'transformations' => [
                    10 => [
                            'mapping' => [
                                    'table' => 'tx_news_domain_model_news',
                                    'referenceField' => 'categories',
                                    'valueMap' => array (
                                        'Brötchen' => 9,
                                        'Bäckersnacks' => 10,
                                        'Körnerbrötchen' => 11,
                                        'Brote' => 17
                                    )                                 
                            ]
                    ]
            ]              
        ],      
        1 => [
            'field' => 'Allergene',
            'transformations' => [
                    10 => [
                            'mapping' => [
                                    'table' => 'tx_news_domain_model_news',
                                    'referenceField' => 'categories',
                                    'multipleValuesSeparator' => ',',
                                    'valueMap' => array (
                                        'GLUTEN' => 14,
                                        'SESAMSAMEN' => 15,
                                        'MILCH' => 16,
                                        'SOJA' => 18,
                                    )                                    
                            ]
                    ],
                    20 => [
                                        'trim' => true
                    ]                   
            ]            
        ]        
];`

So this is, what i have at the moment. the "Allergene" Part works, but not in Combination with "Artikelgruppe"

**Comment by marexx** [comment]
And an other question, is it possible to manipulate a string before using it.
I get something like that: 
Z:\Produktbilder\Fotos_Komplette Sammlung\Brötchen\Sesambrötchen_neu.jpg
\\bbn-server\mavesoft\mavebake\Produktbilder\Fotos_Komplette Sammlung\Stangenware\Lattenkracher_NEU.jpg

for the images i want to use. So i have to trim everything but the filename. Is that possible?
--



--

**Comment by marexx** [comment]
so the Path Problem is solved with the linktransformation Class:
    public function absolutizeUrls($record, $index, $params): string
    {
        $host = $params['host'];
        $text = $record[$index];

        $basename = preg_replace('/^.+\\\\/', '', $text);      
          
        $text = $host.'/'.$basename;
        return $text;
    }

**Comment by marexx** [comment]
Did you find any Solution for this?

**Comment by fsuter** [comment]
No, I haven't had time to try. I'm very busy these days. Sorry.

**Comment by marexx** [comment]
I have a solution thats works for me. with a hook "preprocessRawRecordset"

    public function preprocessRawRecordset($record, $pObj): array
    {
        $i = 0;
        foreach ($record as &$value) {
            $record[$i]['categories']  = $record[$i]['categories'].','.$record[$i]['Allergene'];
            $i++;
        }
        return $record;
    }

**Comment by fsuter** [comment]
Glad that you found a way to work things out.
