### ISSUE TITLE
How to use a hook

### ISSUE THREAD

**Issue by marexx** [cobwebch/external_import#90]
Can somebody give me an example how to use a hook.
I want to use the "preprocessRawRecordset" to combine different fields before processing,

**Comment by fsuter** [comment]
There's an example in externalimport_tut: https://github.com/cobwebch/externalimport_tut/blob/master/Classes/Hook/ExternalImport.php

It's not the same hook, but maybe it helps you.

**Comment by marexx** [comment]
thnx. got it.
