### ISSUE TITLE
Refresh slug field on updated records

### ISSUE THREAD

**Issue by martinavk** [cobwebch/external_import#94]
If records got updated, the slug field in the database won't get refreshed. Is there a plan to include this into the extension?

I'm using the extension to import News. When they get created, the slug (=path_segment field in the news) will be filled according to the title field. But if a record only got upated and the title changed, the slug field "path_segment" needs to be updated as well. 

It would be great if this feature would get included into the extension. If not, what would be the best way to include it? Userfunc/Transformation, Custom ProccessStep, Hook?
Thanks!

**Comment by fsuter** [comment]
Hmm, I never thought about slugs, so there's nothing that External Import can do automatically. As far as I can see, the slug is automatically created by the TYPO3 Core when a new record is imported. So I wonder if explicitly setting the slug on update will work or if the Core will ignore it. This is worth a try.

If you think that it's safe to generate the slug for each record, you can use a Userfunc. If the Core itself does not check for uniqueness, then maybe it's better to use a custom Step, as you will have access to the whole data and thus be able to check unicity of slugs yourself.

Last possibility, you could use the `datamapPostProcess` hook to change the slug for just the updated records.

HTH

**Comment by martinavk** [comment]
Well, there is a SlugHelper Class from the Typo3 Core, that provides functions to generate the slug - and even build a unique slug for. I decided to use the `datamapPostProcess` hook. I'm adding my code, maybe you want to reconsider including it into the exentsion.

```
public function datamapPostProcess($table, $records, $pObj)
{
    // I've set the storagePID in an env variable 
    // and overridden the extension variable in the AdditionalConfigratution with it
    $storageUid = getenv('UID_NEWS_RECORDS'); 

    $fieldConfig = $GLOBALS['TCA'][$table]['columns']['path_segment']['config'];
    $slugHelper = GeneralUtility::makeInstance(SlugHelper::class, $table, 'path_segment', $fieldConfig);
    $connection = GeneralUtility::makeInstance(ConnectionPool::class)->getConnectionForTable('pages');
    $queryBuilder = $connection->createQueryBuilder();

    foreach ($records as $recordUid => $record) {
        if ($record['tx_externalimport:status'] == 'update') {
            $state = RecordStateFactory::forName($table)->fromArray($record, $storageUid, $recordUid);
            $slug = $slugHelper->generate($record, $storageUid);
            $uniqueSlug = $slugHelper->buildSlugForUniqueInSite($slug, $state);

            // Save Slug
            $queryBuilder
                ->update($table)
                ->where(
                    $queryBuilder->expr()->eq(
                        'uid',
                        $queryBuilder->createNamedParameter($recordUid, \PDO::PARAM_INT)
                    )
                )
                ->set('path_segment', $uniqueSlug)// Function "createNamedParameter" is NOT needed here!
                ->execute();
        }
    }
    return $records;
}
```

**Comment by fsuter** [comment]
Thanks for the information and for sharing your code. I will consider this issue for a future version of the extension. I'm leaving this ticket open as a reminder.

**Comment by fsuter** [comment]
Resolves with above commit
