### ISSUE TITLE
Question language overlay

### ISSUE THREAD

**Issue by glucka** [cobwebch/external_import#96]
hi @fsuter 
First of all thank you very much for this extension! 
I hope you enjoy the book 'Proust and the Squid' ;)

Can you give me a tip how can i create language overlays in import process?
The main problem is, i have only one referenceUid for 2 language like here:
https://forge.typo3.org/issues/76109

**Comment by fsuter** [comment]
You have to create an import configuration for each language. You will set the sys_language_uid field to fixed value and you have to map the l10n_parent field in the configuration for the translation. You can isolate the records of each language by using the trick described in the Forge ticket that you mention.

Is that enough information? Do you have more specific questions?

And thanks again for the book. I haven't read it yet.

**Comment by glucka** [comment]
I think i understand now :)
I post my config codes here if works.
Thanks!

**Comment by glucka** [comment]
I can set fixed value over userFunc, but it must be exist a simpler way :)
I cannot find in the docu sorry.

**Comment by fsuter** [comment]
Seems like you deleted your previous comment about setting fixed value. Anyway, if it helps, it's a transformation property and it's described here:
https://docs.typo3.org/typo3cms/extensions/external_import/Administration/Transformations/Index.html#value

**Comment by glucka** [comment]
Thank you @fsuter ! I found it in the meantime!

**Comment by infabo** [comment]
I stumbled upon this issue and I guess this needs some more documenation. I was not able to properly configure the translaton overly.

* I created a second configuration on the same TCA-table

First config has 

```
  'external' => [
        'general' => [
            0 => [
                'connector' => 'feed',
                'parameters' => [
                    'uri' => 'https://some-xml.de',
                    'encoding' => 'utf8'
                ],
                'data' => 'xml',
                'nodetype' => 'job',
                'enforcePid' => true,
                'referenceUid' => 'StellenID',
                'pid' => 189,
                'priority' => 10,
                'group' => 'group0',
                'description' => 'Import of vacancies DE',
                'updateSlugs' => true,
                'where_clause' => 'sys_language_uid = ' . 0
            ],
            1 => [
                'connector' => 'feed',
                'parameters' => [
                    'uri' => 'https://some-xml.en',
                    'encoding' => 'utf8'
                ],
                'data' => 'xml',
                'nodetype' => 'job',
                'enforcePid' => true,
                'referenceUid' => 'StellenID',
                'pid' => 189,
                'priority' => 10,
                'group' => 'vacancies_group',
                'description' => 'Import of vacancies EN',
                'updateSlugs' => true,
                'where_clause' => 'sys_language_uid = ' . 1
            ]
        ]
    ],
```

* sys_language_uid col config looks like

```        'sys_language_uid' => [
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.language',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'special' => 'languages',
                'items' => [
                    [
                        'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.allLanguages',
                        -1,
                        'flags-multiple'
                    ],
                ],
                'default' => 0,
            ],
            'external' => [
                0 => [
                    'transformations' => [
                        10 => [
                            'value' => 0
                        ]
                    ]
                ],
                0 => [
                    'transformations' => [
                        10 => [
                            'value' => 1
                        ]
                    ]
                ],
            ]
        ],
```

## How can the l10n_parent relation built?

The `referenceUid` is in both XMLs the same.

**Comment by fsuter** [comment]
I agree that this would need more documentation (there's actually an open issue in the tutorial: https://github.com/cobwebch/externalimport_tut/issues/2, but I never got around to doing it yet).

What you need is to created an "external" configuration for the "l10n_parent" field, the external field is the one containing the "referenceUid" and you need to apply a "mapping" transformation to the table itself. This should resolve the reference to the parent record.

**Comment by infabo** [comment]
Thanks! I guess it would work but sadly found out, that in my case the non-default language records do not use the same `referenceUid`. So there is no translation-relation ROFL in my current use-case.

**Comment by fsuter** [comment]
Oh, how's that even possible o_O Well, good luck!

**Comment by infabo** [comment]
It isn't possible. ¯_(ツ)_/¯
