### ISSUE TITLE
import self-referential data

### ISSUE THREAD

**Issue by abohntek** [cobwebch/external_import#97]
Is it possible to import self-referential  data? I tried it by setting up 2 external TCA configs, where the first one just imports the data and the second one only import the self-references by synchronizing with the already imported data.

My TCA Code for table_intern:

`external => [

            0 => [
               'connector' => 'sql',
                'parameters' => [
                   ....
                ],
               'referenceUid' => 'id_extern',
            ],
            1 => [
                'connector' => 'sql',
                'parameters' => [
                   ....
                ],
                'referenceUid' => 'id_extern',
                'disabledOperations' => 'insert,delete',
            ]
        ]
`

`id_extern => [

         'external' => [
                0 => [
                    'field' => 'ID'
                ]
            ]
]
`
`
'ref_id_extern' => ['external' => [

                1 => [
                    'field' => 'ref_self_id',
                    'transformations' => [
                        10 => [
                            'mapping' => [
                                'table' => 'table_intern',
                                'referenceField' => 'id_extern'
                            ]
                        ]
                    ]
                ]
            ]
 ]`

But when I start the importer it always displays "0 existing record(s) updated".  May there exist some work around for this?

**Comment by fsuter** [comment]
I'm not sure what the problem is at first sight, but could you try to use a single configuration? External Import is able to detect self-references and should handle them fine in a single import.

**Comment by abohntek** [comment]
Thank u very much! It works out of the box as u wrote.
