### ISSUE TITLE
MM and multipleValuesSeparator doesn't work

### ISSUE THREAD

**Issue by abohntek** [cobwebch/external_import#98]
I tried to map sys_categories with news from an external source where I get Categories seperated by ",".  The mapping only works with: 

```
'transformations' => [
            10 => [
'mapping' => [
                    'table' => 'sys_category',
                    'referenceField' => 'title',
                    'default' => '',
                    'multipleValuesSeparator' => ','
                ] ] ]
```

But not with 

```
'MM' => [
            'mapping' => [
                'table' => 'sys_category',
                'referenceField' => 'title',
                'default' => '',
                'multipleValuesSeparator' => ','
            ],
            'multiple' => true
        ]
```
It seems the mapping of categories for news still works without the MM, so I could do it without MM. Anyway its a bug I guess so I opened this issue.

**Comment by fsuter** [comment]
Thanks for reporting. I haven't personally used the MM in a while and I would need to look at the code again, but I think that actually the MM and multipleValuesSeparator properties are not compatible. If that is the case, it should be documented, so having this issue is good anyway ;-).

**Comment by fsuter** [comment]
I can confirm that this does not work. The MM property is used to indicate that the external data in denormalized, in which case it makes no sense to use a multipleValuesSeparator. Maybe this page helps: https://docs.typo3.org/typo3cms/extensions/external_import/stable/User/MappingData/Index.html#user-mapping-data-mm

Anyway, there's no bug to fix, but I'll update the documentation.
