### ISSUE TITLE
userFunc: get currently saved value from t3 database

### ISSUE THREAD

**Issue by abohntek** [cobwebch/external_import#99]
Hey,

is it possible to receive the current field value of the typo3 related table, when values only should be updated?

I want to transform a field value from an external database and override it with the current one but only if the currently saved value in the typo3 database fulfills some conditions. Otherwise I don´t want to update the t3 database field value. Exist there an elegant way to achieve this goal?

**Comment by fsuter** [comment]
No elegant way, I'm afraid. You'll have to use a custom step or a user function for this.
Actually the philosophy of external_import was to limit the built-in features (it already has quite a lot) and instead allow for many ways of hooking code at various places to manipulate data. The rationale is that data import often requires very specific transformations. Trying to build them all inside the extension would result in code bloat.

**Comment by abohntek** [comment]
Ok, I understand. Then I will write my custom code for this. Thank you for the fast reply!
